// uni: universo · plat: plataforma · s: nota IMDb · d: duración (min) · h: cuándo ocurre
// r: año de estreno · exp: ruta express · opt: opcional · res: resumen · n: nota de visionado
// dir: dirección · cast: reparto principal (enlaza a la filmografía de cada actor)
export const DATA = [
{
  saga: "xmen", titulo: "Saga X-Men (Fox)", uni: "Tierra-10005",
  desc: "El universo mutante de 20th Century Fox, ordenado por cuándo ocurre cada historia. Termina en Logan; el puente con el UCM es Deadpool y Lobezno, al final del UCM.",
  eras: [
    { era: "Los orígenes", rango: "1962–1992", c: ["#E8A93C", "#8A5408"], items: [
      { id: "first-class", t: "X-Men: Primera generación", h: "1962", r: 2011, s: 7.7, d: 132, plat: "Disney+",
        dir: "Matthew Vaughn", cast: ["James McAvoy", "Michael Fassbender", "Jennifer Lawrence"],
        res: "Charles y Erik se conocen en plena Guerra Fría y fundan los primeros X-Men." },
      { id: "origins-wolverine", t: "X-Men Orígenes: Lobezno", h: "1845–1979", r: 2009, s: 6.5, d: 107, plat: "Disney+",
        dir: "Gavin Hood", cast: ["Hugh Jackman", "Liev Schreiber", "Ryan Reynolds"],
        res: "El pasado de Logan: el programa Arma X y el adamantium.", n: "Salta entre décadas; su grueso ocurre en 1979." },
      { id: "dofp", t: "X-Men: Días del futuro pasado", h: "1973 y 2023", r: 2014, s: 7.9, d: 132, plat: "Disney+",
        dir: "Bryan Singer", cast: ["Hugh Jackman", "James McAvoy", "Michael Fassbender"],
        res: "Lobezno viaja a 1973 para evitar el futuro de los Centinelas.", n: "Reinicia la línea temporal desde 1973." },
      { id: "apocalypse", t: "X-Men: Apocalipsis", h: "1983", r: 2016, s: 6.9, d: 144, plat: "Disney+",
        dir: "Bryan Singer", cast: ["James McAvoy", "Michael Fassbender", "Oscar Isaac"],
        res: "El primer mutante de la historia despierta y quiere rehacer el mundo." },
      { id: "dark-phoenix", t: "X-Men: Fénix Oscura", h: "1992", r: 2019, s: 5.7, d: 114, plat: "Disney+",
        dir: "Simon Kinberg", cast: ["Sophie Turner", "James McAvoy", "Jessica Chastain"],
        res: "Jean Grey absorbe una fuerza cósmica que no puede controlar." },
    ]},
    { era: "La trilogía original y Lobezno", rango: "2000–2029", c: ["#C98A10", "#6E4204"], items: [
      { id: "xmen1", t: "X-Men", h: "2000", r: 2000, s: 7.3, d: 104, plat: "Disney+",
        dir: "Bryan Singer", cast: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen"],
        res: "Magneto amenaza a la humanidad y los X-Men de Xavier debutan en el cine." },
      { id: "x2", t: "X-Men 2", h: "2003", r: 2003, s: 7.4, d: 134, plat: "Disney+",
        dir: "Bryan Singer", cast: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen"],
        res: "Un militar ataca la mansión y obliga a mutantes rivales a aliarse." },
      { id: "last-stand", t: "X-Men: La decisión final", h: "2006", r: 2006, s: 6.6, d: 104, plat: "Disney+",
        dir: "Brett Ratner", cast: ["Hugh Jackman", "Halle Berry", "Ian McKellen"],
        res: "Una «cura» mutante y el regreso de Fénix lo dividen todo." },
      { id: "the-wolverine", t: "Lobezno inmortal", h: "2013", r: 2013, s: 6.7, d: 126, plat: "Disney+",
        dir: "James Mangold", cast: ["Hugh Jackman", "Tao Okamoto", "Rila Fukushima"],
        res: "Logan viaja a Japón y se enfrenta a su propia inmortalidad." },
      { id: "deadpool1", t: "Deadpool", h: "2016", r: 2016, s: 8.0, d: 108, plat: "Disney+", exp: true,
        dir: "Tim Miller", cast: ["Ryan Reynolds", "Morena Baccarin", "Ed Skrein"],
        res: "Wade Wilson busca venganza sin dejar de romper la cuarta pared." },
      { id: "deadpool2", t: "Deadpool 2", h: "2018", r: 2018, s: 7.6, d: 119, plat: "Disney+", exp: true,
        dir: "David Leitch", cast: ["Ryan Reynolds", "Josh Brolin", "Zazie Beetz"],
        res: "Wade monta la X-Force para proteger a un chaval del viajero temporal Cable." },
      { id: "new-mutants", t: "Los Nuevos Mutantes", h: "~2020", r: 2020, s: 5.3, d: 94, plat: "Disney+", opt: true,
        dir: "Josh Boone", cast: ["Maisie Williams", "Anya Taylor-Joy", "Charlie Heaton"],
        res: "Cinco jóvenes mutantes atrapados en un hospital lleno de secretos.", n: "Historia independiente; su fecha exacta es ambigua." },
      { id: "logan", t: "Logan", h: "2029", r: 2017, s: 8.1, d: 137, plat: "Disney+", exp: true,
        dir: "James Mangold", cast: ["Hugh Jackman", "Patrick Stewart", "Dafne Keen"],
        res: "Un Logan envejecido cruza el país para salvar a una niña como él.", n: "El cierre de la saga." },
      { id: "xmen97", t: "X-Men '97", h: "—", r: 2024, s: 8.4, d: 300, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Beau DeMayo (creador)",
        res: "Continuación directa de la serie animada de los 90, y a su altura." },
    ]},
  ],
},
{
  saga: "ucm", titulo: "Universo Cinematográfico de Marvel", uni: "Tierra-616",
  desc: "Películas, series de Disney+ y especiales en orden cronológico de la historia, desde 1943 hasta hoy.",
  eras: [
    { era: "Los orígenes", rango: "1943–2012", c: ["#2B5DA8", "#122A55"], items: [
      { id: "cap1", t: "Capitán América: El primer vengador", h: "1943–45", r: 2011, s: 6.9, d: 124, plat: "Disney+", exp: true,
        dir: "Joe Johnston", cast: ["Chris Evans", "Hayley Atwell", "Hugo Weaving"],
        res: "Steve Rogers se convierte en el supersoldado que planta cara a Hydra." },
      { id: "agent-carter", t: "Agente Carter (T1–T2)", h: "1946–47", r: 2015, s: 7.9, d: 756, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Markus y McFeely (creadores)", cast: ["Hayley Atwell", "James D'Arcy"],
        res: "Peggy Carter funda en la posguerra lo que acabará siendo S.H.I.E.L.D." },
      { id: "capmarvel", t: "Capitana Marvel", h: "1995", r: 2019, s: 6.8, d: 123, plat: "Disney+",
        dir: "Anna Boden y Ryan Fleck", cast: ["Brie Larson", "Samuel L. Jackson", "Jude Law"],
        res: "Carol Danvers recompone su pasado en plena guerra entre Kree y Skrulls." },
      { id: "ironman1", t: "Iron Man", h: "2008", r: 2008, s: 7.9, d: 126, plat: "Disney+", exp: true,
        dir: "Jon Favreau", cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges"],
        res: "Tony Stark construye en una cueva la armadura que lo cambia todo.",
        n: "En Civil War, Visión sitúa la revelación de Stark 8 años antes de 2016." },
      { id: "ironman2", t: "Iron Man 2", h: "2011", r: 2010, s: 6.9, d: 124, plat: "Disney+",
        dir: "Jon Favreau", cast: ["Robert Downey Jr.", "Mickey Rourke", "Scarlett Johansson"],
        res: "Tony lidia con su legado y con Vanko mientras el reactor lo envenena.",
        n: "La «Gran Semana de Fury»: Iron Man 2, Thor y El increíble Hulk ocurren la misma semana de 2011." },
      { id: "thor1", t: "Thor", h: "2011", r: 2011, s: 7.0, d: 115, plat: "Disney+",
        dir: "Kenneth Branagh", cast: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston"],
        res: "Thor es desterrado a la Tierra hasta volver a ser digno del martillo." },
      { id: "hulk", t: "El increíble Hulk", h: "2011", r: 2008, s: 6.6, d: 112, plat: "Disney+",
        dir: "Louis Leterrier", cast: ["Edward Norton", "Liv Tyler", "Tim Roth"],
        res: "Bruce Banner huye del ejército que quiere convertir su monstruo en arma." },
      { id: "avengers1", t: "Los Vengadores", h: "2012", r: 2012, s: 8.0, d: 143, plat: "Disney+", exp: true,
        dir: "Joss Whedon", cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        res: "Loki invade Nueva York y el equipo se une por primera vez." },
    ]},
    { era: "Tras Nueva York", rango: "2012–2015", c: ["#2E8C7A", "#123F36"], items: [
      { id: "ironman3", t: "Iron Man 3", h: "2012, Navidad", r: 2013, s: 7.1, d: 130, plat: "Disney+",
        dir: "Shane Black", cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Ben Kingsley"],
        res: "Tony, sin armadura y con ansiedad, investiga al Mandarín." },
      { id: "thor2", t: "Thor: El mundo oscuro", h: "2013", r: 2013, s: 6.8, d: 112, plat: "Disney+",
        dir: "Alan Taylor", cast: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston"],
        res: "Los elfos oscuros persiguen el Éter, una de las Gemas del Infinito." },
      { id: "cap2", t: "Capitán América: El Soldado de Invierno", h: "2014", r: 2014, s: 7.8, d: 136, plat: "Disney+", exp: true,
        dir: "Anthony y Joe Russo", cast: ["Chris Evans", "Scarlett Johansson", "Sebastian Stan"],
        res: "Steve descubre que S.H.I.E.L.D. está podrido por dentro." },
      { id: "gotg1", t: "Guardianes de la Galaxia", h: "2014", r: 2014, s: 8.0, d: 121, plat: "Disney+",
        dir: "James Gunn", cast: ["Chris Pratt", "Zoe Saldaña", "Dave Bautista"],
        res: "Un ladrón, dos matones, una asesina y un árbol salvan la galaxia." },
      { id: "gotg2", t: "Guardianes de la Galaxia Vol. 2", h: "2014", r: 2017, s: 7.6, d: 136, plat: "Disney+",
        dir: "James Gunn", cast: ["Chris Pratt", "Zoe Saldaña", "Kurt Russell"],
        res: "Quill conoce a su padre y la familia elegida se pone a prueba." },
      { id: "oneshots", t: "Marvel One-Shots (cortos)", h: "2011–14", r: 2011, d: 62, tipo: "esp", opt: true, plat: "Disney+",
        dir: "Varios directores", cast: ["Hayley Atwell", "Clark Gregg", "Ben Kingsley"],
        res: "Los cortos de S.H.I.E.L.D.: El Consultor, Item 47, Agent Carter y All Hail the King.",
        n: "Rellenan huecos entre películas de las Fases 1 y 2." },
      { id: "aos", t: "Agents of S.H.I.E.L.D. (T1–T7)", h: "2013–20", r: 2013, s: 7.5, d: 5700, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Tancharoen y Whedon (creadores)", cast: ["Clark Gregg", "Chloe Bennet", "Ming-Na Wen"],
        res: "Coulson vive: la serie que acompañó al UCM desde Los Vengadores hasta el Blip.",
        n: "Sus 3 primeras temporadas se entrelazan con las películas; su canon es discutido desde la Fase 4." },
      { id: "daredevil", t: "Daredevil (T1–T3)", h: "2015–18", r: 2015, s: 8.6, d: 2030, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Drew Goddard (creador)", cast: ["Charlie Cox", "Vincent D'Onofrio", "Deborah Ann Woll"],
        res: "Matt Murdock contra Kingpin: la joya de las series de calle.", n: "Imprescindible antes de Daredevil: Born Again." },
      { id: "jessicajones", t: "Jessica Jones (T1–T3)", h: "2015–18", r: 2015, s: 7.9, d: 1750, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Melissa Rosenberg (creadora)", cast: ["Krysten Ritter", "David Tennant", "Rachael Taylor"],
        res: "Una detective privada con superfuerza y un pasado que la persigue." },
      { id: "lukecage", t: "Luke Cage (T1–T2)", h: "2016–18", r: 2016, s: 7.3, d: 1300, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Cheo Hodari Coker (creador)", cast: ["Mike Colter", "Mahershala Ali", "Alfre Woodard"],
        res: "El héroe a prueba de balas de Harlem." },
      { id: "ironfist", t: "Iron Fist (T1–T2)", h: "2017–18", r: 2017, s: 6.4, d: 1250, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Scott Buck (creador)", cast: ["Finn Jones", "Jessica Henwick"],
        res: "Danny Rand vuelve de K'un-Lun con el poder del Puño de Hierro.", n: "La más floja del bloque; puedes saltártela." },
      { id: "defenders", t: "The Defenders", h: "2017", r: 2017, s: 7.3, d: 400, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Douglas Petrie y Marco Ramirez", cast: ["Charlie Cox", "Krysten Ritter", "Mike Colter"],
        res: "Los cuatro héroes de calle se unen contra La Mano." },
      { id: "punisher", t: "The Punisher (T1–T2)", h: "2016–18", r: 2017, s: 8.5, d: 1430, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Steve Lightfoot (creador)", cast: ["Jon Bernthal", "Ben Barnes", "Ebon Moss-Bachrach"],
        res: "Frank Castle a la guerra contra quienes destrozaron su vida.", n: "Bernthal vuelve como Castigador en Born Again." },
      { id: "ultron", t: "Vengadores: La era de Ultrón", h: "2015", r: 2015, s: 7.3, d: 141, plat: "Disney+", exp: true,
        dir: "Joss Whedon", cast: ["Robert Downey Jr.", "Chris Hemsworth", "James Spader"],
        res: "Una IA creada por Stark decide que la paz mundial exige extinguirnos." },
      { id: "antman1", t: "Ant-Man", h: "2015", r: 2015, s: 7.3, d: 117, plat: "Disney+",
        dir: "Peyton Reed", cast: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas"],
        res: "Un ladrón con buen corazón hereda el traje que encoge." },
    ]},
    { era: "Civil War y el camino a Thanos", rango: "2016–2018", c: ["#C8102E", "#5C0916"], items: [
      { id: "civilwar", t: "Capitán América: Civil War", h: "2016", r: 2016, s: 7.8, d: 147, plat: "Disney+", exp: true,
        dir: "Anthony y Joe Russo", cast: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson"],
        res: "Los Acuerdos de Sokovia parten a los Vengadores en dos bandos." },
      { id: "blackwidow", t: "Viuda Negra", h: "2016", r: 2021, s: 6.7, d: 134, plat: "Disney+",
        dir: "Cate Shortland", cast: ["Scarlett Johansson", "Florence Pugh", "David Harbour"],
        res: "Natasha salda cuentas con la Sala Roja que la creó.", n: "Ocurre justo después de Civil War." },
      { id: "blackpanther", t: "Black Panther", h: "2016", r: 2018, s: 7.3, d: 134, plat: "Disney+",
        dir: "Ryan Coogler", cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
        res: "T'Challa defiende el trono de Wakanda frente a Killmonger." },
      { id: "homecoming", t: "Spider-Man: Homecoming", h: "2016", r: 2017, s: 7.4, d: 133, plat: "Disney+", exp: true,
        dir: "Jon Watts", cast: ["Tom Holland", "Michael Keaton", "Zendaya"],
        res: "Peter Parker compagina el instituto con la caza del Buitre." },
      { id: "inhumans", t: "Inhumans", h: "2016", r: 2017, s: 5.0, d: 344, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Scott Buck (creador)", cast: ["Anson Mount", "Serinda Swan"],
        res: "La familia real inhumana huye de un golpe de estado en la Luna.", n: "Solo para completistas: la peor valorada de todo Marvel." },
      { id: "drstrange", t: "Doctor Strange", h: "2016–17", r: 2016, s: 7.5, d: 115, plat: "Disney+", exp: true,
        dir: "Scott Derrickson", cast: ["Benedict Cumberbatch", "Tilda Swinton", "Mads Mikkelsen"],
        res: "Un cirujano arrogante pierde las manos y encuentra las artes místicas." },
      { id: "ragnarok", t: "Thor: Ragnarok", h: "2017", r: 2017, s: 7.9, d: 130, plat: "Disney+",
        dir: "Taika Waititi", cast: ["Chris Hemsworth", "Cate Blanchett", "Tom Hiddleston"],
        res: "Thor, gladiador en Sakaar, contra su hermana Hela." },
      { id: "cloakdagger", t: "Cloak & Dagger (T1–T2)", h: "2017", r: 2018, s: 6.5, d: 900, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Joe Pokaski (creador)", cast: ["Olivia Holt", "Aubrey Joseph"],
        res: "Dos adolescentes de Nueva Orleans con poderes de luz y oscuridad enlazados." },
      { id: "runaways", t: "Runaways (T1–T3)", h: "2017–18", r: 2017, s: 6.9, d: 1485, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Schwartz y Savage (creadores)", cast: ["Rhenzy Feliz", "Lyrica Okano"],
        res: "Seis chavales descubren que sus padres son una organización criminal." },
      { id: "antman2", t: "Ant-Man y la Avispa", h: "2018", r: 2018, s: 7.0, d: 118, plat: "Disney+",
        dir: "Peyton Reed", cast: ["Paul Rudd", "Evangeline Lilly", "Michelle Pfeiffer"],
        res: "Un rescate en el reino cuántico con la Avispa al mando." },
      { id: "infinitywar", t: "Vengadores: Infinity War", h: "2018", r: 2018, s: 8.4, d: 149, plat: "Disney+", exp: true,
        dir: "Anthony y Joe Russo", cast: ["Robert Downey Jr.", "Josh Brolin", "Chris Hemsworth"],
        res: "Thanos va a por las seis Gemas y nadie está a salvo." },
    ]},
    { era: "El Lapso y Endgame", rango: "2018–2023", c: ["#6D4FA3", "#2E2050"], items: [
      { id: "endgame", t: "Vengadores: Endgame", h: "2018–2023", r: 2019, s: 8.4, d: 181, plat: "Disney+", exp: true,
        dir: "Anthony y Joe Russo", cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
        res: "Cinco años después del chasquido, un último plan: el atraco temporal." },
      { id: "loki1", t: "Loki (T1)", h: "Fuera del tiempo", r: 2021, s: 8.2, d: 300, tipo: "serie", plat: "Disney+", exp: true,
        dir: "Kate Herron", cast: ["Tom Hiddleston", "Owen Wilson", "Sophia Di Martino"],
        res: "Una variante de Loki descubre la TVA y a El Que Permanece." },
      { id: "whatif", t: "What If...? (T1–T3)", h: "Multiverso", r: 2021, s: 7.4, d: 780, tipo: "serie", opt: true, plat: "Disney+", uni: "Multiverso",
        dir: "Bryan Andrews", cast: ["Jeffrey Wright (voz)"],
        res: "El Vigilante recorre versiones alternativas del UCM en animación." },
      { id: "zombies", t: "Marvel Zombies", h: "Multiverso", r: 2025, d: 120, tipo: "serie", opt: true, plat: "Disney+", uni: "Multiverso",
        dir: "Bryan Andrews",
        res: "Un multiverso devorado: los héroes contra la plaga zombi." },
    ]},
    { era: "El mundo tras el Blip", rango: "2023–2024", c: ["#B03A6E", "#521B35"], items: [
      { id: "wandavision", t: "WandaVisión", h: "2023, otoño", r: 2021, s: 7.9, d: 350, tipo: "serie", plat: "Disney+",
        dir: "Matt Shakman", cast: ["Elizabeth Olsen", "Paul Bettany", "Kathryn Hahn"],
        res: "Wanda vive una sitcom perfecta que esconde un duelo terrible." },
      { id: "eternals", t: "Eternals", h: "2023–24", r: 2021, s: 6.3, d: 156, plat: "Disney+",
        dir: "Chloé Zhao", cast: ["Gemma Chan", "Richard Madden", "Angelina Jolie"],
        res: "Seres inmortales que moldearon la historia humana salen de las sombras." },
      { id: "shangchi", t: "Shang-Chi y la leyenda de los Diez Anillos", h: "2024, primavera", r: 2021, s: 7.4, d: 132, plat: "Disney+",
        dir: "Destin Daniel Cretton", cast: ["Simu Liu", "Tony Leung", "Awkwafina"],
        res: "Shang-Chi se enfrenta a su padre y a la organización de los Diez Anillos." },
      { id: "fatws", t: "Falcon y el Soldado de Invierno", h: "2024, primavera", r: 2021, s: 7.1, d: 300, tipo: "serie", plat: "Disney+",
        dir: "Kari Skogland", cast: ["Anthony Mackie", "Sebastian Stan", "Daniel Brühl"],
        res: "Sam y Bucky cargan con el escudo y el legado del Capi." },
      { id: "lovethunder", t: "Thor: Love and Thunder", h: "2024, mayo–junio", r: 2022, s: 6.2, d: 119, plat: "Disney+",
        dir: "Taika Waititi", cast: ["Chris Hemsworth", "Natalie Portman", "Christian Bale"],
        res: "Gorr jura exterminar a los dioses y Jane Foster empuña el Mjolnir.", n: "El análisis de Jane está fechado el 30 de abril de 2024." },
      { id: "moonknight", t: "Caballero Luna", h: "2024, junio", r: 2022, s: 7.3, d: 280, tipo: "serie", plat: "Disney+",
        dir: "Mohamed Diab", cast: ["Oscar Isaac", "May Calamawy", "Ethan Hawke"],
        res: "Un hombre con identidades múltiples al servicio de un dios lunar egipcio.", n: "Sus fases lunares coinciden con junio de 2024." },
      { id: "ffh", t: "Spider-Man: Lejos de casa", h: "2024, verano", r: 2019, s: 7.4, d: 129, plat: "Disney+", exp: true,
        dir: "Jon Watts", cast: ["Tom Holland", "Jake Gyllenhaal", "Zendaya"],
        res: "Peter, de viaje por Europa, hereda más responsabilidad de la que quiere." },
      { id: "sony", t: "El multiverso de Sony (Raimi, Garfield, Venom…)", h: "2002–2024", r: 2002, d: 1330, opt: true, plat: "Netflix / SkyShowtime", uni: "Sony",
        dir: "Sam Raimi, Marc Webb y otros", cast: ["Tobey Maguire", "Andrew Garfield", "Tom Hardy"],
        res: "Los Spider-Man de Maguire y Garfield y los villanos que vuelven en No Way Home.",
        n: "Las dos sagas antiguas ayudan a disfrutar No Way Home; Venom 1–3, Morbius, Madame Web y Kraven son prescindibles." },
      { id: "nwh", t: "Spider-Man: No Way Home", h: "2024, otoño", r: 2021, s: 8.2, d: 148, plat: "Disney+ / Netflix", exp: true,
        dir: "Jon Watts", cast: ["Tom Holland", "Tobey Maguire", "Andrew Garfield"],
        res: "Un hechizo rompe el multiverso: tres generaciones de Spider-Man." },
      { id: "mom", t: "Doctor Strange en el multiverso de la locura", h: "2024, finales", r: 2022, s: 6.9, d: 126, plat: "Disney+", exp: true,
        dir: "Sam Raimi", cast: ["Benedict Cumberbatch", "Elizabeth Olsen", "Xochitl Gomez"],
        res: "Strange y América Chávez huyen por el multiverso de una Wanda rota.", n: "Poco después de No Way Home." },
      { id: "hawkeye", t: "Ojo de Halcón", h: "2024, Navidad", r: 2021, s: 7.5, d: 280, tipo: "serie", plat: "Disney+",
        dir: "Rhys Thomas y Bert & Bertie", cast: ["Jeremy Renner", "Hailee Steinfeld", "Florence Pugh"],
        res: "Clint y Kate Bishop contra el pasado de Ronin, en plena Navidad." },
    ]},
    { era: "La Saga del Multiverso se expande", rango: "2024–2025", c: ["#C86A10", "#5E3004"], items: [
      { id: "shehulk", t: "She-Hulk: Abogada Hulka", h: "2024–25", r: 2022, s: 5.2, d: 315, tipo: "serie", plat: "Disney+",
        dir: "Kat Coiro", cast: ["Tatiana Maslany", "Mark Ruffalo", "Tim Roth"],
        res: "Jennifer Walters, abogada y prima de Hulk, rompe la cuarta pared.", n: "Arranca en octubre de 2024 y se extiende hasta agosto de 2025." },
      { id: "wakandaforever", t: "Black Panther: Wakanda Forever", h: "2025, mayo", r: 2022, s: 6.7, d: 161, plat: "Disney+",
        dir: "Ryan Coogler", cast: ["Letitia Wright", "Angela Bassett", "Tenoch Huerta"],
        res: "Wakanda llora a T'Challa mientras se enfrenta a Namor y Talokan." },
      { id: "echo", t: "Echo", h: "2025, mayo", r: 2024, s: 6.1, d: 200, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Sydney Freeland", cast: ["Alaqua Cox", "Vincent D'Onofrio"],
        res: "Maya Lopez vuelve a casa huyendo de Kingpin.", n: "Cinco meses después de Ojo de Halcón." },
      { id: "msmarvel", t: "Ms. Marvel", h: "2025, septiembre", r: 2022, s: 6.1, d: 270, tipo: "serie", plat: "Disney+",
        dir: "Adil El Arbi y Bilall Fallah", cast: ["Iman Vellani", "Matt Lintz"],
        res: "Kamala Khan, superfán de los Vengadores, descubre sus propios poderes." },
      { id: "ironheart", t: "Ironheart", h: "2025, octubre", r: 2025, s: 4.2, d: 270, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Chinaka Hodge (creadora)", cast: ["Dominique Thorne", "Anthony Ramos"],
        res: "Riri Williams construye su propia armadura y paga el precio." },
      { id: "secretinvasion", t: "Invasión Secreta", h: "2025, noviembre", r: 2023, s: 5.9, d: 270, tipo: "serie", plat: "Disney+",
        dir: "Ali Selim", cast: ["Samuel L. Jackson", "Ben Mendelsohn", "Olivia Colman"],
        res: "Skrulls infiltrados en los gobiernos y un Fury sin apoyos." },
      { id: "marvels", t: "The Marvels", h: "2025, finales", r: 2023, s: 5.5, d: 105, plat: "Disney+",
        dir: "Nia DaCosta", cast: ["Brie Larson", "Teyonah Parris", "Iman Vellani"],
        res: "Carol, Mónica y Kamala intercambian posiciones cada vez que usan sus poderes." },
      { id: "holiday", t: "Especial Felices Fiestas de los Guardianes", h: "2025, Navidad", r: 2022, s: 7.0, d: 44, tipo: "esp", plat: "Disney+",
        dir: "James Gunn", cast: ["Chris Pratt", "Pom Klementieff", "Kevin Bacon"],
        res: "Los Guardianes secuestran a Kevin Bacon para animar a Quill por Navidad." },
      { id: "werewolf", t: "Werewolf by Night", h: "2025, 29 dic", r: 2022, s: 7.0, d: 53, tipo: "esp", plat: "Disney+",
        dir: "Michael Giacchino", cast: ["Gael García Bernal", "Laura Donnelly"],
        res: "Cazadores de monstruos en una noche de homenaje al terror clásico." },
    ]},
    { era: "Fases 5 y 6: rumbo a Doomsday", rango: "2026 →", c: ["#3E8E3E", "#153E15"], items: [
      { id: "wonderman", t: "Wonder Man", h: "2026–27", r: 2026, d: 240, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Destin Daniel Cretton", cast: ["Yahya Abdul-Mateen II", "Ben Kingsley"],
        res: "Simon Williams, actor y superhéroe, en una sátira de Hollywood." },
      { id: "quantumania", t: "Ant-Man y la Avispa: Quantumanía", h: "2026, julio", r: 2023, s: 6.0, d: 125, plat: "Disney+",
        dir: "Peyton Reed", cast: ["Paul Rudd", "Jonathan Majors", "Michelle Pfeiffer"],
        res: "La familia Ant-Man queda atrapada en el reino cuántico con Kang." },
      { id: "loki2", t: "Loki (T2)", h: "Fuera del tiempo", r: 2023, s: 8.2, d: 300, tipo: "serie", plat: "Disney+", exp: true,
        dir: "Justin Benson y Aaron Moorhead", cast: ["Tom Hiddleston", "Owen Wilson", "Ke Huy Quan"],
        res: "Loki intenta salvar la TVA y, con ella, todas las líneas temporales." },
      { id: "deadpool3", t: "Deadpool y Lobezno", h: "2024*", r: 2024, s: 7.6, d: 128, plat: "Disney+", exp: true, uni: "Multiverso",
        dir: "Shawn Levy", cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
        res: "Wade recluta a un Lobezno de otro universo para salvar el suyo.",
        n: "El puente entre la saga X-Men y el UCM. Vela después de Loki T2, que introduce la TVA." },
      { id: "gotg3", t: "Guardianes de la Galaxia Vol. 3", h: "2026, septiembre", r: 2023, s: 7.9, d: 150, plat: "Disney+",
        dir: "James Gunn", cast: ["Chris Pratt", "Zoe Saldaña", "Bradley Cooper (voz)"],
        res: "El pasado de Rocket y la despedida del equipo de James Gunn." },
      { id: "agatha", t: "Agatha, ¿quién si no?", h: "2026, octubre", r: 2024, s: 7.1, d: 342, tipo: "serie", plat: "Disney+",
        dir: "Jac Schaeffer", cast: ["Kathryn Hahn", "Joe Locke", "Aubrey Plaza"],
        res: "Agatha Harkness recorre el Camino de las Brujas para recuperar su poder." },
      { id: "daredevil-ba", t: "Daredevil: Born Again (T1–T2)", h: "2025–27", r: 2025, s: 8.3, d: 810, tipo: "serie", plat: "Disney+",
        dir: "Dario Scardapane (showrunner)", cast: ["Charlie Cox", "Vincent D'Onofrio", "Margarita Levieva"],
        res: "Matt Murdock contra un Wilson Fisk convertido en alcalde de Nueva York." },
      { id: "bravenewworld", t: "Capitán América: Brave New World", h: "2027, abril", r: 2025, s: 5.8, d: 118, plat: "Disney+",
        dir: "Julius Onah", cast: ["Anthony Mackie", "Harrison Ford", "Danny Ramirez"],
        res: "Sam Wilson, ya Capitán América, ante una conspiración con Ross de presidente." },
      { id: "thunderbolts", t: "Thunderbolts*", h: "2027, otoño", r: 2025, s: 7.2, d: 127, plat: "Disney+", exp: true,
        dir: "Jake Schreier", cast: ["Florence Pugh", "Sebastian Stan", "Lewis Pullman"],
        res: "Un grupo de antihéroes rotos, el Vacío, y el asterisco mejor guardado del año." },
      { id: "eyeswakanda", t: "Eyes of Wakanda", h: "Pasado de Wakanda", r: 2025, d: 120, tipo: "serie", opt: true, plat: "Disney+",
        dir: "Todd Harris",
        res: "Guerreros wakandianos a lo largo de la historia, en animación." },
      { id: "ff", t: "Los 4 Fantásticos: First Steps", h: "Años 60", r: 2025, s: 7.2, d: 115, plat: "Disney+", exp: true, uni: "Tierra-828",
        dir: "Matt Shakman", cast: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn"],
        res: "La primera familia de Marvel contra Galactus en un mundo retrofuturista.",
        n: "Ocurre en otro universo; conecta con Doomsday." },
      { id: "brandnewday", t: "Spider-Man: Brand New Day", h: "2025–28", r: 2026, d: 130, plat: "Cine", exp: true,
        dir: "Destin Daniel Cretton", cast: ["Tom Holland", "Sadie Sink", "Jon Bernthal"],
        res: "Nueva etapa de Peter, solo y sin que nadie lo recuerde, tras No Way Home.", n: "Abarca los años universitarios de MJ y Ned; estrenada en julio de 2026." },
      { id: "doomsday", t: "Vengadores: Doomsday", h: "Próximamente", r: 2026, exp: true, plat: "Cine · dic 2026",
        dir: "Anthony y Joe Russo", cast: ["Robert Downey Jr.", "Chris Hemsworth", "Vanessa Kirby"],
        res: "Vengadores, 4 Fantásticos y X-Men frente al Doctor Doom de Robert Downey Jr." },
    ]},
  ],
},
{
  saga: "comics", titulo: "Cómics esenciales", uni: "Papel",
  desc: "Los cómics que inspiraron las películas y las historias imprescindibles de cada personaje, en orden de lectura recomendado. No hace falta leerlos todos: elige los que te llamen.",
  eras: [
    { era: "X-Men: los imprescindibles", rango: "1975–2019", c: ["#8A5FB8", "#3A2760"], items: [
      { id: "c-giantsize", t: "Giant-Size X-Men #1", a: "Wein y Cockrum", r: 1975, plat: "Panini / Marvel Unlimited",
        res: "Nace el equipo moderno: Lobezno, Tormenta, Rondador Nocturno…" },
      { id: "c-darkphoenix", t: "La Saga de Fénix Oscura", a: "Claremont y Byrne", r: 1980, plat: "Panini / Marvel Unlimited",
        res: "La cima de los X-Men; base de La decisión final y Fénix Oscura." },
      { id: "c-dofp", t: "Días del futuro pasado", a: "Claremont y Byrne", r: 1981, plat: "Panini / Marvel Unlimited",
        res: "El viaje temporal que adaptó la película de 2014." },
      { id: "c-godloves", t: "Dios ama, el hombre mata", a: "Claremont y Anderson", r: 1982, plat: "Panini / Marvel Unlimited",
        res: "La novela gráfica que inspiró X-Men 2." },
      { id: "c-wolverine82", t: "Lobezno (miniserie)", a: "Claremont y Miller", r: 1982, plat: "Panini / Marvel Unlimited",
        res: "El Lobezno en Japón que adaptó Lobezno inmortal." },
      { id: "c-newxmen", t: "New X-Men: E de Extinción", a: "Morrison y Quitely", r: 2001, opt: true, plat: "Panini / Marvel Unlimited",
        res: "La etapa que modernizó a los mutantes para el siglo XXI." },
      { id: "c-astonishing", t: "Astonishing X-Men: Dotados", a: "Whedon y Cassaday", r: 2004, plat: "Panini / Marvel Unlimited",
        res: "Perfecta como primer cómic de X-Men." },
      { id: "c-houseofm", t: "Dinastía de M", a: "Bendis y Coipel", r: 2005, opt: true, plat: "Panini / Marvel Unlimited",
        res: "«No más mutantes»: tres palabras que cambian el universo Marvel." },
      { id: "c-oldmanlogan", t: "El viejo Logan", a: "Millar y McNiven", r: 2008, plat: "Panini / Marvel Unlimited",
        res: "El western crepuscular que inspiró Logan." },
      { id: "c-hoxpox", t: "Dinastía de X / Potencias de X", a: "Hickman", r: 2019, plat: "Panini / Marvel Unlimited",
        res: "El renacimiento moderno; probable base de los X-Men del UCM." },
    ]},
    { era: "Vengadores y el camino del UCM", rango: "1966–2015", c: ["#6D4FA3", "#2E2050"], items: [
      { id: "c-galactus", t: "Los 4 Fantásticos: La trilogía de Galactus", a: "Lee y Kirby", r: 1966, plat: "Panini / Marvel Unlimited",
        res: "El devorador de mundos: la base de First Steps." },
      { id: "c-infinitygauntlet", t: "El Guantelete del Infinito", a: "Starlin y Pérez", r: 1991, plat: "Panini / Marvel Unlimited",
        res: "Thanos y el chasquido originales: Infinity War y Endgame." },
      { id: "c-ultimates", t: "The Ultimates", a: "Millar y Hitch", r: 2002, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El tono y el aspecto del UCM salen de aquí." },
      { id: "c-extremis", t: "Iron Man: Extremis", a: "Ellis y Granov", r: 2005, opt: true, plat: "Panini / Marvel Unlimited",
        res: "La base de Iron Man 3." },
      { id: "c-wintersoldier", t: "Capitán América: El Soldado de Invierno", a: "Brubaker y Epting", r: 2005, plat: "Panini / Marvel Unlimited",
        res: "La mejor etapa del Capi, adaptada casi literalmente en 2014." },
      { id: "c-civilwar", t: "Civil War", a: "Millar y McNiven", r: 2006, plat: "Panini / Marvel Unlimited",
        res: "El enfrentamiento entre héroes que adaptó la película." },
      { id: "c-planethulk", t: "Planet Hulk", a: "Pak", r: 2006, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El Hulk gladiador que viste Ragnarok." },
      { id: "c-gotg", t: "Guardianes de la Galaxia", a: "Abnett y Lanning", r: 2008, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El equipo cósmico que James Gunn llevó al cine." },
      { id: "c-thoraaron", t: "Thor: El carnicero de dioses", a: "Aaron y Ribić", r: 2012, plat: "Panini / Marvel Unlimited",
        res: "Gorr, el villano de Love and Thunder, en su versión más aterradora." },
      { id: "c-secretwars", t: "Secret Wars", a: "Hickman y Ribić", r: 2015, plat: "Panini / Marvel Unlimited",
        res: "El evento hacia el que apuntan Doomsday y Secret Wars." },
    ]},
    { era: "Héroes de calle y rarezas", rango: "1986–2015", c: ["#5A3E8E", "#251844"], items: [
      { id: "c-bornagain", t: "Daredevil: Born Again", a: "Miller y Mazzucchelli", r: 1986, plat: "Panini / Marvel Unlimited",
        res: "Da nombre a la serie y es una obra maestra del cómic." },
      { id: "c-deadpoolkelly", t: "Deadpool de Joe Kelly", a: "Kelly y McGuinness", r: 1997, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El humor de las películas nace aquí." },
      { id: "c-ultimatespider", t: "Ultimate Spider-Man", a: "Bendis y Bagley", r: 2000, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El Peter Parker adolescente que inspiró a Tom Holland." },
      { id: "c-hawkeyefraction", t: "Ojo de Halcón", a: "Fraction y Aja", r: 2012, plat: "Panini / Marvel Unlimited",
        res: "Base directa de la serie; una joya del diseño de cómic." },
      { id: "c-msmarvel", t: "Ms. Marvel: Fuera de lo normal", a: "Wilson y Alphona", r: 2014, opt: true, plat: "Panini / Marvel Unlimited",
        res: "El debut de Kamala Khan, fresco y ganador del Hugo." },
      { id: "c-visionking", t: "La Visión", a: "King y Walta", r: 2015, opt: true, plat: "Panini / Marvel Unlimited",
        res: "Inquietante y precioso; alimenta WandaVisión." },
    ]},
  ],
},
]

// Próximos estrenos anunciados (fecha en ISO o null si está por confirmar)
export const ESTRENOS = [
  { t: "Vengadores: Doomsday", fecha: "2026-12-18", tipo: "Película · Cine",
    n: "El Doctor Doom de Robert Downey Jr. contra Vengadores, 4 Fantásticos y X-Men." },
  { t: "Vision Quest", fecha: null, aprox: "Finales de 2026", tipo: "Serie · Disney+",
    n: "Visión busca recuperar su memoria; con Paul Bettany y James Spader (Ultrón)." },
  { t: "Avengers: Secret Wars", fecha: "2027-12-17", tipo: "Película · Cine",
    n: "El cierre de la Saga del Multiverso." },
  { t: "X-Men (UCM)", fecha: null, aprox: "En desarrollo", tipo: "Película",
    n: "El reinicio mutante dentro del UCM, tras Secret Wars." },
]

export const JOYA_MIN = 7.5
export const KEY = "maraton-marvel-v1"
