// Traducción al inglés de los textos escritos a mano (sinopsis, notas,
// guías, eras, estrenos, multiverso, logros y aristas del mapa). Las claves
// son el texto EXACTO en español de España del código fuente; se consulta
// cuando el idioma elegido en Ajustes es English. Un texto sin entrada se
// enseña en español: al añadir textos nuevos a data.js hay que traerlos aquí.
export const EN_TEXTOS = {
  "Multiverso": "Multiverse",
  "Papel": "Print",
  "2 (mitad y final)": "2 (mid- and post-credits)",
  "1 al final": "1 at the end",
  "1 a mitad": "1 mid-credits",
  "5 escenas": "5 scenes",
  "Saga X-Men (Fox)": "X-Men Saga (Fox)",
  "Universo Cinematográfico de Marvel": "Marvel Cinematic Universe",
  "Cómics esenciales": "Essential comics",
  "La bóveda de animación": "The animation vault",
  "El universo mutante de 20th Century Fox son DOS líneas temporales: la original, que Lobezno borra al viajar a 1973 en Días del futuro pasado, y la nueva, que nace ahí y termina en Logan. Se ven en ese orden —no por año de la historia— para que nadie muera antes de aparecer vivo. El puente con el UCM es Deadpool y Lobezno, al final del UCM.": "The 20th Century Fox mutant universe is TWO timelines: the original one, which Wolverine erases by traveling to 1973 in Days of Future Past, and the new one, which is born there and ends with Logan. You watch them in that order — not by in-story year — so nobody dies before showing up alive. The bridge to the MCU is Deadpool & Wolverine, at the end of the MCU.",
  "La idea": "The idea",
  "En Días del futuro pasado, Lobezno viaja de 2023 a 1973 y evita que Mística mate a Trask, el creador de los Centinelas. Todo lo que pasó entre 1973 y 2023 en la línea original queda borrado y arranca una línea nueva. Hasta DoFP ves la original; desde Apocalipsis, la nueva.": "In Days of Future Past, Wolverine travels from 2023 to 1973 and stops Mystique from killing Trask, the creator of the Sentinels. Everything that happened between 1973 and 2023 in the original timeline is erased and a new one begins. Up to DoFP you're watching the original; from Apocalypse on, the new one.",
  "Cómo saber en qué línea estás": "How to tell which timeline you're in",
  "Por los actores. Patrick Stewart, Ian McKellen, Rebecca Romijn y Famke Janssen son la línea original (2000–2023). James McAvoy, Michael Fassbender, Jennifer Lawrence y Sophie Turner son los jóvenes: 1962 y 1973 son comunes a las dos líneas, y toda la línea nueva es suya. Hugh Jackman está en ambas porque su mente viaja.": "By the actors. Patrick Stewart, Ian McKellen, Rebecca Romijn and Famke Janssen are the original timeline (2000–2023). James McAvoy, Michael Fassbender, Jennifer Lawrence and Sophie Turner are the young ones: 1962 and 1973 are shared by both timelines, and the whole new timeline is theirs. Hugh Jackman is in both because his mind travels.",
  "Mística": "Mystique",
  "Muere en Fénix Oscura (1992, línea nueva). La que ves viva en X-Men y X-Men 2 es la de la línea borrada. No es un error de orden.": "She dies in Dark Phoenix (1992, new timeline). The one you see alive in X-Men and X-Men 2 is from the erased timeline. It's not an ordering mistake.",
  "Lo que no cuadra y conviene aceptar": "What doesn't add up and is best just accepted",
  "Xavier camina en Orígenes y en 1973 pese a quedar paralítico en 1962 (DoFP lo explica con un suero; Orígenes, no). En el 2023 de DoFP Lobezno vuelve a tener garras de adamantium sin explicación. Las edades no casan entre 1983 y 2000. Fox nunca cuidó la continuidad, y no hay orden que lo arregle.": "Xavier walks in Origins and in 1973 despite being paralyzed in 1962 (DoFP explains it with a serum; Origins doesn't). In DoFP's 2023, Wolverine has adamantium claws again with no explanation. The ages don't line up between 1983 and 2000. Fox never cared about continuity, and no viewing order can fix it.",
  "Las series": "The series",
  "The Gifted, Legion, la serie animada y X-Men '97 van por libre: no afectan a las películas ni las películas a ellas.": "The Gifted, Legion, the animated series and X-Men '97 stand on their own: they don't affect the films, and the films don't affect them.",
  "La línea original": "The original timeline",
  "Charles y Erik se conocen en plena Guerra Fría y fundan los primeros X-Men.": "Charles and Erik meet at the height of the Cold War and found the first X-Men.",
  "El pasado de Logan: el programa Arma X y el adamantium.": "Logan's past: the Weapon X program and the adamantium.",
  "Salta entre décadas; su grueso ocurre en 1979. La bala de adamantium del final le borra la memoria: por eso en X-Men (2000) no recuerda nada.": "It jumps across decades; most of it takes place in 1979. The adamantium bullet at the end wipes his memory: that's why he remembers nothing in X-Men (2000).",
  "Magneto amenaza a la humanidad y los X-Men de Xavier debutan en el cine.": "Magneto threatens humanity and Xavier's X-Men make their big-screen debut.",
  "Línea original: esta Mística (Rebecca Romijn) está viva porque la línea aún no ha sido borrada.": "Original timeline: this Mystique (Rebecca Romijn) is alive because the timeline hasn't been erased yet.",
  "Un militar ataca la mansión y obliga a mutantes rivales a aliarse.": "A military man attacks the mansion and forces rival mutants to join forces.",
  "Una «cura» mutante y el regreso de Fénix lo dividen todo.": "A mutant “cure” and the return of the Phoenix split everything apart.",
  "Mueren Jean, Cíclope y Xavier, y Magneto pierde sus poderes: todo esto será borrado en Días del futuro pasado. Quédate a la escena tras los créditos, que explica cómo vuelve Xavier.": "Jean, Cyclops and Xavier die, and Magneto loses his powers: all of this will be erased in Days of Future Past. Stay for the scene after the credits — it explains how Xavier comes back.",
  "Logan viaja a Japón y se enfrenta a su propia inmortalidad.": "Logan travels to Japan and faces his own immortality.",
  "Sus post-créditos son la bisagra de la saga: Xavier y Magneto, con poderes otra vez, avisan de Trask y los Centinelas.": "Its post-credits scene is the hinge of the whole saga: Xavier and Magneto, powers restored, warn about Trask and the Sentinels.",
  "prepara Días del futuro pasado": "sets up Days of Future Past",
  "Lobezno viaja a 1973 para evitar el futuro de los Centinelas.": "Wolverine travels to 1973 to prevent the Sentinel future.",
  "Aquí se parte la saga: el 2023 de los Centinelas es el futuro de la línea original (la de X-Men 1, 2 y 3), y el viaje a 1973 la borra. Todo lo que viene después ocurre en la línea nueva.": "This is where the saga splits: the Sentinel 2023 is the future of the original timeline (the one from X-Men 1, 2 and 3), and the trip to 1973 erases it. Everything that comes after happens in the new timeline.",
  "La línea nueva": "The new timeline",
  "El primer mutante de la historia despierta y quiere rehacer el mundo.": "The first mutant in history awakens and wants to remake the world.",
  "Primera película que ocurre entera en la línea nueva.": "First film that takes place entirely in the new timeline.",
  "Jean Grey absorbe una fuerza cósmica que no puede controlar.": "Jean Grey absorbs a cosmic force she cannot control.",
  "Mística muere aquí, en la línea nueva; la Mística de X-Men 1 y 2 vivía en la línea borrada.": "Mystique dies here, in the new timeline; the Mystique from X-Men 1 and 2 lived in the erased one.",
  "Wade Wilson busca venganza sin dejar de romper la cuarta pared.": "Wade Wilson hunts for revenge while never once dropping the fourth-wall breaks.",
  "al estilo Ferris Bueller": "Ferris Bueller style",
  "Wade monta la X-Force para proteger a un chaval del viajero temporal Cable.": "Wade puts together X-Force to protect a kid from the time traveler Cable.",
  "Confirma la línea nueva: en la mansión aparecen los X-Men jóvenes de Apocalipsis. La escena post-créditos que mata al Deadpool de Orígenes es un chiste; no cuenta.": "It confirms the new timeline: the young X-Men from Apocalypse show up at the mansion. The post-credits scene that kills the Origins Deadpool is a joke; it doesn't count.",
  "imprescindible: reescribe el final": "essential: it rewrites the ending",
  "Cinco jóvenes mutantes atrapados en un hospital lleno de secretos.": "Five young mutants trapped in a hospital full of secrets.",
  "Historia independiente; su fecha exacta es ambigua.": "Standalone story; its exact date is ambiguous.",
  "Un Logan envejecido cruza el país para salvar a una niña como él.": "An aged Logan crosses the country to save a girl just like him.",
  "El cierre de la saga. Un futuro posible de la línea nueva, no una continuación exacta de Fénix Oscura: un ataque de Xavier mató a los X-Men fuera de cámara.": "The saga's closer. A possible future of the new timeline, not an exact continuation of Dark Phoenix: an attack by Xavier killed the X-Men off-screen.",
  "Las series, con continuidad propia": "The series, with their own continuity",
  "Una familia huye con sus hijos mutantes en un mundo sin X-Men.": "A family goes on the run with their mutant kids in a world without X-Men.",
  "Continuidad paralela del universo Fox.": "Parallel continuity within the Fox universe.",
  "David Haller, el hijo de Xavier, entre la esquizofrenia y un poder inmenso.": "David Haller, Xavier's son, caught between schizophrenia and immense power.",
  "La rareza de autor del universo X-Men; continuidad propia.": "The auteur oddity of the X-Men universe; its own continuity.",
  "La serie de los 90 que definió a los X-Men para una generación.": "The '90s series that defined the X-Men for a generation.",
  "Prólogo directo de X-Men '97: los foros la consideran imprescindible antes de '97.": "Direct prologue to X-Men '97: the forums consider it essential viewing before '97.",
  "Continuación directa de la serie animada de los 90, y a su altura.": "A direct continuation of the '90s animated series, and every bit its equal.",
  "Películas, series de Disney+ y especiales en orden cronológico de la historia, desde 1943 hasta hoy.": "Films, Disney+ series and specials in story-chronological order, from 1943 to today.",
  "A diferencia de los X-Men, el UCM es una sola línea: nada se borra. Los saltos que notarás vienen de dos cosas, el Chasquido y el multiverso, y las dos se explican aquí.": "Unlike the X-Men, the MCU is a single timeline: nothing gets erased. The jumps you'll notice come from two things, the Snap and the multiverse, and both are explained here.",
  "El Chasquido y el Lapso": "The Snap and the Blip",
  "En Infinity War (2018) Thanos borra a la mitad del universo. Endgame salta cinco años, a 2023, y los devuelve. Todo lo posterior habla del «Lapso» (Blip): los desaparecidos no envejecieron, y por eso Peter Parker sigue en el instituto en 2024.": "In Infinity War (2018) Thanos wipes out half the universe. Endgame jumps five years ahead, to 2023, and brings them back. Everything after that talks about the “Blip”: the vanished didn't age, which is why Peter Parker is still in high school in 2024.",
  "Los viajes en el tiempo de Endgame no borran nada": "Endgame's time travel doesn't erase anything",
  "Crean ramas. El Loki de 2012 escapa con el Teseracto y de ahí nacen la serie Loki, la TVA y las variantes: por eso Loki va justo después de Endgame aunque esté «fuera del tiempo». What If…?, Marvel Zombies y Your Friendly Neighborhood Spider-Man son otros universos: se ven ahí, pero no tocan la línea principal.": "It creates branches. The 2012 Loki escapes with the Tesseract, and from there come the Loki series, the TVA and the variants: that's why Loki goes right after Endgame even though it's “outside of time”. What If…?, Marvel Zombies and Your Friendly Neighborhood Spider-Man are other universes: you watch them there, but they don't touch the main timeline.",
  "El multiverso": "The multiverse",
  "No Way Home trae a los Spider-Man de las películas de Sony (por eso ese bloque va justo antes), y Multiverso de la locura y Loki T2 lo consolidan. Los 4 Fantásticos viven en otra Tierra, en unos años 60 alternativos. Y Deadpool y Lobezno viene del universo Fox: por eso la saga X-Men entera se ve antes y esa película casi al final, como puente. Doomsday junta a todos.": "No Way Home brings in the Spider-Men from the Sony films (that's why that block goes right before it), and Multiverse of Madness and Loki S2 cement it. The Fantastic Four live on another Earth, in an alternate 1960s. And Deadpool & Wolverine comes from the Fox universe: that's why the whole X-Men saga is watched earlier and that film goes near the very end, as the bridge. Doomsday brings everyone together.",
  "Las series de Netflix y ABC": "The Netflix and ABC series",
  "Agents of S.H.I.E.L.D., Daredevil, Jessica Jones y compañía se hicieron aparte y durante años no contaron. Daredevil: Born Again las recupera con los mismos actores. Se pueden saltar sin perder el hilo de las películas.": "Agents of S.H.I.E.L.D., Daredevil, Jessica Jones and company were made separately and for years didn't count. Daredevil: Born Again brings them back with the same actors. You can skip them without losing the thread of the films.",
  "Cómo saber dónde estás": "How to tell where you are",
  "Si mencionan el Lapso, estás después de 2023. Si Thanos sigue vivo, antes de 2018. Si alguien habla de variantes o de la TVA, estás en la saga del multiverso.": "If they mention the Blip, you're after 2023. If Thanos is still alive, before 2018. If someone talks about variants or the TVA, you're in the Multiverse Saga.",
  "Los orígenes": "The origins",
  "Steve Rogers se convierte en el supersoldado que planta cara a Hydra.": "Steve Rogers becomes the super-soldier who stands up to Hydra.",
  "Peggy Carter funda en la posguerra lo que acabará siendo S.H.I.E.L.D.": "In the post-war years, Peggy Carter founds what will become S.H.I.E.L.D.",
  "Carol Danvers recompone su pasado en plena guerra entre Kree y Skrulls.": "Carol Danvers pieces her past back together in the middle of the Kree–Skrull war.",
  "Tony Stark construye en una cueva la armadura que lo cambia todo.": "Tony Stark builds, in a cave, the armor that changes everything.",
  "En Civil War, Visión sitúa la revelación de Stark 8 años antes de 2016.": "In Civil War, Vision places Stark's reveal 8 years before 2016.",
  "la escena que arrancó el UCM": "the scene that kicked off the MCU",
  "Tony lidia con su legado y con Vanko mientras el reactor lo envenena.": "Tony wrestles with his legacy and with Vanko while the reactor poisons him.",
  "La «Gran Semana de Fury»: Iron Man 2, Thor y El increíble Hulk ocurren la misma semana de 2011.": "“Fury's Big Week”: Iron Man 2, Thor and The Incredible Hulk all happen in the same week of 2011.",
  "Thor es desterrado a la Tierra hasta volver a ser digno del martillo.": "Thor is banished to Earth until he proves worthy of the hammer again.",
  "Bruce Banner huye del ejército que quiere convertir su monstruo en arma.": "Bruce Banner flees the army that wants to turn his monster into a weapon.",
  "la escena de Tony va antes de los créditos": "Tony's scene comes before the credits",
  "Loki invade Nueva York y el equipo se une por primera vez.": "Loki invades New York and the team assembles for the first time.",
  "la del final es la shawarma": "the end one is the shawarma scene",
  "Tras Nueva York": "After New York",
  "Tony, sin armadura y con ansiedad, investiga al Mandarín.": "Tony, without his armor and battling anxiety, investigates the Mandarin.",
  "Los elfos oscuros persiguen el Éter, una de las Gemas del Infinito.": "The Dark Elves chase the Aether, one of the Infinity Stones.",
  "Steve descubre que S.H.I.E.L.D. está podrido por dentro.": "Steve discovers S.H.I.E.L.D. is rotten from the inside.",
  "Un ladrón, dos matones, una asesina y un árbol salvan la galaxia.": "A thief, two thugs, an assassin and a tree save the galaxy.",
  "Quill conoce a su padre y la familia elegida se pone a prueba.": "Quill meets his father and the found family is put to the test.",
  "récord del UCM": "an MCU record",
  "Diez travesuras del pequeño Groot entre Guardianes Vol. 2 y Vol. 3.": "Ten bits of mischief from little Groot between Guardians Vol. 2 and Vol. 3.",
  "Los cortos de S.H.I.E.L.D.: El Consultor, Item 47, Agent Carter y All Hail the King.": "The S.H.I.E.L.D. shorts: The Consultant, Item 47, Agent Carter and All Hail the King.",
  "Rellenan huecos entre películas de las Fases 1 y 2.": "They fill in gaps between the Phase 1 and 2 films.",
  "Coulson vive: la serie que acompañó al UCM desde Los Vengadores hasta el Blip.": "Coulson lives: the series that ran alongside the MCU from The Avengers to the Blip.",
  "Sus 3 primeras temporadas se entrelazan con las películas; su canon es discutido desde la Fase 4.": "Its first 3 seasons interweave with the films; its canon status has been debated since Phase 4.",
  "Matt Murdock contra Kingpin: la joya de las series de calle.": "Matt Murdock versus Kingpin: the crown jewel of the street-level series.",
  "Imprescindible antes de Daredevil: Born Again.": "Essential before Daredevil: Born Again.",
  "Una detective privada con superfuerza y un pasado que la persigue.": "A private detective with super strength and a past that haunts her.",
  "El héroe a prueba de balas de Harlem.": "Harlem's bulletproof hero.",
  "Danny Rand vuelve de K'un-Lun con el poder del Puño de Hierro.": "Danny Rand returns from K'un-Lun with the power of the Iron Fist.",
  "La más floja del bloque; puedes saltártela.": "The weakest of the bunch; feel free to skip it.",
  "Los cuatro héroes de calle se unen contra La Mano.": "The four street-level heroes unite against the Hand.",
  "Frank Castle a la guerra contra quienes destrozaron su vida.": "Frank Castle at war with the people who destroyed his life.",
  "Bernthal vuelve como Castigador en Born Again.": "Bernthal returns as the Punisher in Born Again.",
  "Una IA creada por Stark decide que la paz mundial exige extinguirnos.": "An AI created by Stark decides world peace requires our extinction.",
  "Un ladrón con buen corazón hereda el traje que encoge.": "A thief with a good heart inherits the shrinking suit.",
  "Civil War y el camino a Thanos": "Civil War and the road to Thanos",
  "Los Acuerdos de Sokovia parten a los Vengadores en dos bandos.": "The Sokovia Accords split the Avengers into two camps.",
  "Natasha salda cuentas con la Sala Roja que la creó.": "Natasha settles scores with the Red Room that made her.",
  "Ocurre justo después de Civil War.": "Takes place right after Civil War.",
  "T'Challa defiende el trono de Wakanda frente a Killmonger.": "T'Challa defends the throne of Wakanda against Killmonger.",
  "Peter Parker compagina el instituto con la caza del Buitre.": "Peter Parker juggles high school with hunting the Vulture.",
  "la del final es una broma del Capi": "the end one is a joke from Cap",
  "La familia real inhumana huye de un golpe de estado en la Luna.": "The Inhuman royal family flees a coup on the Moon.",
  "Solo para completistas: la peor valorada de todo Marvel.": "For completists only: the worst-rated title in all of Marvel.",
  "Un cirujano arrogante pierde las manos y encuentra las artes místicas.": "An arrogant surgeon loses his hands and finds the mystic arts.",
  "Thor, gladiador en Sakaar, contra su hermana Hela.": "Thor, a gladiator on Sakaar, against his sister Hela.",
  "Dos adolescentes de Nueva Orleans con poderes de luz y oscuridad enlazados.": "Two New Orleans teenagers with linked powers of light and darkness.",
  "Seis chavales descubren que sus padres son una organización criminal.": "Six kids discover their parents are a criminal organization.",
  "Un rescate en el reino cuántico con la Avispa al mando.": "A rescue in the Quantum Realm with the Wasp in charge.",
  "la de mitad es clave para Endgame": "the mid-credits one is key for Endgame",
  "Thanos va a por las seis Gemas y nadie está a salvo.": "Thanos comes for all six Stones and no one is safe.",
  "presenta a Capitana Marvel": "introduces Captain Marvel",
  "El Lapso y Endgame": "The Blip and Endgame",
  "Cinco años después del chasquido, un último plan: el atraco temporal.": "Five years after the snap, one last plan: the time heist.",
  "solo se oye un martilleo: homenaje a Iron Man": "you only hear hammering: a tribute to Iron Man",
  "Una variante de Loki descubre la TVA y a El Que Permanece.": "A Loki variant discovers the TVA and He Who Remains.",
  "El Vigilante recorre versiones alternativas del UCM en animación.": "The Watcher tours alternate versions of the MCU in animation.",
  "Un multiverso devorado: los héroes contra la plaga zombi.": "A devoured multiverse: the heroes against the zombie plague.",
  "Un Peter Parker alternativo, con Norman Osborn de mentor en vez de Tony Stark.": "An alternate Peter Parker, with Norman Osborn as his mentor instead of Tony Stark.",
  "La T2 (otoño 2026) trae el simbionte Venom, a Gwen Stacy y al Daredevil de Charlie Cox.": "Season 2 (fall 2026) brings the Venom symbiote, Gwen Stacy and Charlie Cox's Daredevil.",
  "El mundo tras el Blip": "The world after the Blip",
  "Wanda vive una sitcom perfecta que esconde un duelo terrible.": "Wanda lives inside a perfect sitcom that hides a terrible grief.",
  "Seres inmortales que moldearon la historia humana salen de las sombras.": "Immortal beings who shaped human history step out of the shadows.",
  "Shang-Chi se enfrenta a su padre y a la organización de los Diez Anillos.": "Shang-Chi faces his father and the Ten Rings organization.",
  "Sam y Bucky cargan con el escudo y el legado del Capi.": "Sam and Bucky carry the weight of the shield and Cap's legacy.",
  "Gorr jura exterminar a los dioses y Jane Foster empuña el Mjolnir.": "Gorr vows to exterminate the gods and Jane Foster wields Mjolnir.",
  "El análisis de Jane está fechado el 30 de abril de 2024.": "Jane's test results are dated April 30, 2024.",
  "Un hombre con identidades múltiples al servicio de un dios lunar egipcio.": "A man with multiple identities in the service of an Egyptian moon god.",
  "Sus fases lunares coinciden con junio de 2024.": "Its moon phases match June 2024.",
  "Peter, de viaje por Europa, hereda más responsabilidad de la que quiere.": "Peter, on a trip across Europe, inherits more responsibility than he wants.",
  "la de mitad cambia el status quo: no te la saltes": "the mid-credits one changes the status quo: don't skip it",
  "Los Spider-Man de Maguire y Garfield y los villanos que vuelven en No Way Home.": "The Maguire and Garfield Spider-Men and the villains who return in No Way Home.",
  "Las dos sagas antiguas ayudan a disfrutar No Way Home; Venom 1–3, Morbius, Madame Web y Kraven son prescindibles.": "The two older sagas help you enjoy No Way Home; Venom 1–3, Morbius, Madame Web and Kraven are skippable.",
  "Un hechizo rompe el multiverso: tres generaciones de Spider-Man.": "A spell cracks the multiverse open: three generations of Spider-Man.",
  "la del final es el tráiler de Multiverse of Madness": "the end one is the Multiverse of Madness trailer",
  "Strange y América Chávez huyen por el multiverso de una Wanda rota.": "Strange and America Chavez flee across the multiverse from a broken Wanda.",
  "Poco después de No Way Home.": "Shortly after No Way Home.",
  "Clint y Kate Bishop contra el pasado de Ronin, en plena Navidad.": "Clint and Kate Bishop face Ronin's past, right in the middle of Christmas.",
  "La Saga del Multiverso se expande": "The Multiverse Saga expands",
  "Jennifer Walters, abogada y prima de Hulk, rompe la cuarta pared.": "Jennifer Walters, lawyer and Hulk's cousin, breaks the fourth wall.",
  "Arranca en octubre de 2024 y se extiende hasta agosto de 2025.": "It starts in October 2024 and stretches into August 2025.",
  "Wakanda llora a T'Challa mientras se enfrenta a Namor y Talokan.": "Wakanda mourns T'Challa while facing Namor and Talokan.",
  "Maya Lopez vuelve a casa huyendo de Kingpin.": "Maya Lopez comes back home, on the run from Kingpin.",
  "Cinco meses después de Ojo de Halcón.": "Five months after Hawkeye.",
  "Kamala Khan, superfán de los Vengadores, descubre sus propios poderes.": "Kamala Khan, Avengers superfan, discovers powers of her own.",
  "Riri Williams construye su propia armadura y paga el precio.": "Riri Williams builds her own armor and pays the price.",
  "Skrulls infiltrados en los gobiernos y un Fury sin apoyos.": "Skrulls infiltrating governments and a Fury with no backup.",
  "Carol, Mónica y Kamala intercambian posiciones cada vez que usan sus poderes.": "Carol, Monica and Kamala swap places every time they use their powers.",
  "un guiño que importa para Doomsday": "a nod that matters for Doomsday",
  "Los Guardianes secuestran a Kevin Bacon para animar a Quill por Navidad.": "The Guardians kidnap Kevin Bacon to cheer Quill up for Christmas.",
  "Cazadores de monstruos en una noche de homenaje al terror clásico.": "Monster hunters on a night paying homage to classic horror.",
  "Fases 5 y 6: rumbo a Doomsday": "Phases 5 and 6: the road to Doomsday",
  "Simon Williams, actor y superhéroe, en una sátira de Hollywood.": "Simon Williams, actor and superhero, in a Hollywood satire.",
  "La familia Ant-Man queda atrapada en el reino cuántico con Kang.": "The Ant-Man family gets trapped in the Quantum Realm with Kang.",
  "Loki intenta salvar la TVA y, con ella, todas las líneas temporales.": "Loki tries to save the TVA and, with it, every timeline.",
  "Wade recluta a un Lobezno de otro universo para salvar el suyo.": "Wade recruits a Wolverine from another universe to save his own.",
  "El puente entre la saga X-Men y el UCM; la Tierra-10005 colapsa al morir su «ser ancla» en Logan. Vela después de Loki T2.": "The bridge between the X-Men saga and the MCU; Earth-10005 collapses when its “anchor being” dies in Logan. Watch it after Loki S2.",
  "El pasado de Rocket y la despedida del equipo de James Gunn.": "Rocket's past and the farewell of James Gunn's team.",
  "Agatha Harkness recorre el Camino de las Brujas para recuperar su poder.": "Agatha Harkness walks the Witches' Road to get her power back.",
  "Matt Murdock contra un Wilson Fisk convertido en alcalde de Nueva York.": "Matt Murdock against a Wilson Fisk turned mayor of New York.",
  "Frank Castle creía no tener nada que vengar, hasta que Ma Gnucci viene a por él.": "Frank Castle thought he had nothing left to avenge, until Ma Gnucci comes for him.",
  "Tercer especial de Marvel TV; co-escrito por el propio Bernthal.": "Third Marvel TV special; co-written by Bernthal himself.",
  "Sam Wilson, ya Capitán América, ante una conspiración con Ross de presidente.": "Sam Wilson, now Captain America, up against a conspiracy with Ross as president.",
  "Un grupo de antihéroes rotos, el Vacío, y el asterisco mejor guardado del año.": "A group of broken antiheroes, the Void, and the year's best-kept asterisk.",
  "la del final conecta con los 4 Fantásticos": "the end one connects to the Fantastic Four",
  "Guerreros wakandianos a lo largo de la historia, en animación.": "Wakandan warriors throughout history, in animation.",
  "La primera familia de Marvel contra Galactus en un mundo retrofuturista.": "Marvel's first family against Galactus in a retro-futuristic world.",
  "Ocurre en otro universo; conecta con Doomsday.": "Takes place in another universe; connects to Doomsday.",
  "la de mitad presenta al villano de Doomsday": "the mid-credits one introduces the Doomsday villain",
  "Nueva etapa de Peter, solo y sin que nadie lo recuerde, tras No Way Home.": "A new chapter for Peter, alone and remembered by no one, after No Way Home.",
  "Abarca los años universitarios de MJ y Ned; estrenada en julio de 2026.": "It spans MJ and Ned's college years; released in July 2026.",
  "va DESPUÉS de los logos: no te levantes": "it comes AFTER the logos: don't get up",
  "Vengadores, 4 Fantásticos y X-Men frente al Doctor Doom de Robert Downey Jr.": "Avengers, Fantastic Four and X-Men against Robert Downey Jr.'s Doctor Doom.",
  "Los cómics que inspiraron las películas y las historias imprescindibles de cada personaje, en orden de lectura recomendado. No hace falta leerlos todos: elige los que te llamen.": "The comics that inspired the films and each character's essential stories, in recommended reading order. You don't have to read them all: pick the ones that call to you.",
  "X-Men: los imprescindibles": "X-Men: the essentials",
  "Nace el equipo moderno: Lobezno, Tormenta, Rondador Nocturno…": "The modern team is born: Wolverine, Storm, Nightcrawler…",
  "La cima de los X-Men; base de La decisión final y Fénix Oscura.": "The X-Men at their peak; the basis for The Last Stand and Dark Phoenix.",
  "El viaje temporal que adaptó la película de 2014.": "The time-travel story the 2014 film adapted.",
  "La novela gráfica que inspiró X-Men 2.": "The graphic novel that inspired X-Men 2.",
  "El Lobezno en Japón que adaptó Lobezno inmortal.": "Wolverine in Japan: the story The Wolverine adapted.",
  "La etapa que modernizó a los mutantes para el siglo XXI.": "The run that modernized the mutants for the 21st century.",
  "Perfecta como primer cómic de X-Men.": "Perfect as a first X-Men comic.",
  "«No más mutantes»: tres palabras que cambian el universo Marvel.": "“No more mutants”: three words that change the Marvel Universe.",
  "El western crepuscular que inspiró Logan.": "The twilight western that inspired Logan.",
  "El renacimiento moderno; probable base de los X-Men del UCM.": "The modern rebirth; likely basis for the MCU's X-Men.",
  "Vengadores y el camino del UCM": "Avengers and the road to the MCU",
  "El devorador de mundos: la base de First Steps.": "The devourer of worlds: the basis for First Steps.",
  "Thanos y el chasquido originales: Infinity War y Endgame.": "The original Thanos and the original snap: Infinity War and Endgame.",
  "El tono y el aspecto del UCM salen de aquí.": "The MCU's tone and look come from here.",
  "La base de Iron Man 3.": "The basis for Iron Man 3.",
  "La mejor etapa del Capi, adaptada casi literalmente en 2014.": "Cap's finest run, adapted almost word for word in 2014.",
  "El enfrentamiento entre héroes que adaptó la película.": "The clash between heroes that the film adapted.",
  "El Hulk gladiador que viste Ragnarok.": "The gladiator Hulk you saw in Ragnarok.",
  "El equipo cósmico que James Gunn llevó al cine.": "The cosmic team James Gunn brought to the movies.",
  "Gorr, el villano de Love and Thunder, en su versión más aterradora.": "Gorr, the Love and Thunder villain, at his most terrifying.",
  "El evento hacia el que apuntan Doomsday y Secret Wars.": "The event Doomsday and Secret Wars are pointing toward.",
  "Héroes de calle y rarezas": "Street-level heroes and oddities",
  "Da nombre a la serie y es una obra maestra del cómic.": "It gives the series its name and it's a comics masterpiece.",
  "El humor de las películas nace aquí.": "The humor of the films is born here.",
  "El Peter Parker adolescente que inspiró a Tom Holland.": "The teenage Peter Parker who inspired Tom Holland.",
  "Base directa de la serie; una joya del diseño de cómic.": "Direct basis for the series; a gem of comics design.",
  "El debut de Kamala Khan, fresco y ganador del Hugo.": "Kamala Khan's debut, fresh and a Hugo Award winner.",
  "Inquietante y precioso; alimenta WandaVisión.": "Unsettling and beautiful; it feeds into WandaVision.",
  "Las series animadas de Marvel disponibles hoy en Disney+ España, de los clásicos de los 80 y 90 a la era actual. Fuera de la cronología del maratón: puro disfrute aparte.": "Marvel's animated series available today on Disney+ Spain, from the '80s and '90s classics to the current era. Outside the marathon's chronology: pure enjoyment on the side.",
  "La escuela clásica": "The classic school",
  "Spidey, Estrella de Fuego y Hombre de Hielo compartiendo piso: puro sábado por la mañana.": "Spidey, Firestar and Iceman sharing an apartment: pure Saturday-morning cartoon.",
  "El Tony Stark noventero contra el Mandarín, con armadura modular incluida.": "The '90s Tony Stark against the Mandarin, modular armor included.",
  "La primera familia en su etapa animada clásica, Galactus incluido.": "The first family in their classic animated era, Galactus included.",
  "LA serie de Spider-Man de los 90: sagas del simbionte, los Seis Siniestros y el multiverso arácnido.": "THE '90s Spider-Man series: the symbiote sagas, the Sinister Six and the spider multiverse.",
  "Banner huyendo y machacando en la animada de los 90.": "Banner on the run and smashing away in the '90s animated series.",
  "Cósmica, breve y sorprendentemente seria: el heraldo contra Galactus.": "Cosmic, short and surprisingly serious: the herald against Galactus.",
  "Spidey varado en Contra-Tierra; la rareza de culto del 99.": "Spidey stranded on Counter-Earth; the cult oddity of '99.",
  "La era Disney XD": "The Disney XD era",
  "Para muchos, la mejor serie de los Vengadores jamás hecha.": "For many, the best Avengers series ever made.",
  "Peter rompe la cuarta pared entrenando con S.H.I.E.L.D.": "Peter breaks the fourth wall while training with S.H.I.E.L.D.",
  "El equipo de cine en clave animada, temporada tras temporada.": "The movie team in animated form, season after season.",
  "La familia Hulk al completo grabando su propio reality.": "The whole Hulk family filming their own reality show.",
  "Los Guardianes de Gunn en versión animada de sobremesa.": "Gunn's Guardians in laid-back animated form.",
  "Peter en Horizon High, con Miles y Gwen desde el principio.": "Peter at Horizon High, with Miles and Gwen from the very start.",
  "La era Disney+": "The Disney+ era",
  "El villano cabezón en una sitcom de crisis de los cuarenta, en stop-motion.": "The big-headed villain in a midlife-crisis sitcom, in stop-motion.",
  "Un macaco asesino a sueldo por el Japón nocturno, con fantasma mentor.": "A hitman macaque across nighttime Japan, ghost mentor included.",
  "La puerta de entrada para los peques de la casa.": "The gateway for the little ones in the house.",
  "Lunella, la niña más lista de Marvel, y su T-Rex gigante: energía y estilazo.": "Lunella, Marvel's smartest kid, and her giant T-Rex: energy and style to spare.",
  "Llegan el simbionte Venom, Gwen Stacy y el Daredevil de Charlie Cox.": "The Venom symbiote, Gwen Stacy and Charlie Cox's Daredevil arrive.",
  "Serie · Disney+": "Series · Disney+",
  "Otoño de 2026": "Fall 2026",
  "El Doctor Doom de Robert Downey Jr. contra Vengadores, 4 Fantásticos y X-Men.": "Robert Downey Jr.'s Doctor Doom against Avengers, Fantastic Four and X-Men.",
  "Película · Cine": "Film · Theaters",
  "Visión busca recuperar su memoria; con Paul Bettany y James Spader (Ultrón).": "Vision sets out to recover his memory; with Paul Bettany and James Spader (Ultron).",
  "Finales de 2026": "Late 2026",
  "El cierre de la Saga del Multiverso.": "The close of the Multiverse Saga.",
  "El reinicio mutante dentro del UCM, tras Secret Wars.": "The mutant reboot inside the MCU, after Secret Wars.",
  "Película": "Film",
  "En desarrollo": "In development",
  "El UCM — la Línea Sagrada": "The MCU — the Sacred Timeline",
  "Línea sagrada · activa": "Sacred timeline · active",
  "El universo principal del cine. Se llamó Tierra-199999 hasta que en 2023 Feige lo renombró 616, como el de los cómics. Es la «línea temporal sagrada» que la TVA protege: cada evento nexo que la desvía genera una rama que la TVA poda.": "The main film universe. It was called Earth-199999 until Feige renamed it 616 in 2023, matching the comics. It's the “Sacred Timeline” the TVA protects: every nexus event that pushes it off course spawns a branch the TVA prunes.",
  "La saga X-Men de Fox": "Fox's X-Men saga",
  "Colapsando · ser ancla perdido": "Collapsing · anchor being lost",
  "El universo mutante de Fox. Su «ser ancla» era Lobezno: tras su muerte en Logan, el universo empezó a desvanecerse, la crisis que Deadpool y Lobezno resuelven destruyendo el Desgarrador Temporal.": "Fox's mutant universe. Its “anchor being” was Wolverine: after his death in Logan, the universe began to fade — the crisis Deadpool & Wolverine resolve by destroying the Time Ripper.",
  "El vertedero del tiempo": "The dumping ground of time",
  "Fin del tiempo · dominio de Alioth": "End of time · Alioth's domain",
  "Donde la TVA arroja todo lo podado: no es destrucción, es exilio. Custodiado por Alioth, alberga variantes de Loki (el clásico, el niño, el caimán…) y reliquias de películas canceladas — el Blade y la Antorcha Humana de otros tiempos. Deadpool y Lobezno demostraron que se puede salir.": "Where the TVA dumps everything it prunes: it's not destruction, it's exile. Guarded by Alioth, it holds Loki variants (Classic, Kid, the alligator…) and relics of canceled films — the Blade and the Human Torch of other eras. Deadpool and Wolverine proved you can get out.",
  "El universo de Raimi": "The Raimi universe",
  "Convergió en No Way Home": "Converged in No Way Home",
  "La trilogía de Tobey Maguire: el Spider-Man con telarañas orgánicas que demostró que el cine de superhéroes podía ser cine serio. Converge con la Tierra-616 en No Way Home.": "The Tobey Maguire trilogy: the Spider-Man with organic webs who proved superhero movies could be serious cinema. It converges with Earth-616 in No Way Home.",
  "El universo de Garfield": "The Garfield universe",
  "El Amazing Spider-Man: los mejores balanceos filmados y la historia con Gwen Stacy. Sony llegó a licenciar la Torre Oscorp para Los Vengadores antes de cancelar la conexión. También converge en No Way Home.": "The Amazing Spider-Man: the best web-swinging ever filmed and the Gwen Stacy story. Sony even licensed Oscorp Tower for The Avengers before canceling the connection. It also converges in No Way Home.",
  "El Venomverso": "The Venomverse",
  "Activo · sin Spider-Man": "Active · no Spider-Man",
  "Venom, Morbius, Madame Web y Kraven: simbiontes de Knull y la Red de la Vida… en un universo Spider-Man sin Spider-Man. Eddie Brock visitó brevemente la Tierra-616 y dejó allí un resto de simbionte que aún no ha estallado.": "Venom, Morbius, Madame Web and Kraven: Knull's symbiotes and the Web of Life… in a Spider-Man universe with no Spider-Man. Eddie Brock briefly visited Earth-616 and left behind a piece of symbiote that hasn't erupted yet.",
  "El mundo de los 4 Fantásticos": "The world of the Fantastic Four",
  "Activo · amenazado por Galactus": "Active · threatened by Galactus",
  "Retrofuturismo de los 60 con tecnología adelantada décadas: los 4 Fantásticos no son los primeros héroes, son los únicos. Un universo de exploración más que de conflicto… hasta Galactus. Conecta con Doomsday.": "1960s retro-futurism with technology decades ahead of its time: the Fantastic Four aren't the first heroes, they're the only ones. A universe of exploration more than conflict… until Galactus. Connects to Doomsday.",
  "El mundo de los Illuminati": "The world of the Illuminati",
  "Activo · sin Illuminati": "Active · no Illuminati",
  "Donde los Vengadores fueron sustituidos por los Illuminati (Captain Carter, Black Bolt, Reed Richards, el Profesor X…), que ejecutaron a su propio Strange por usar el Darkhold. La Wanda de la 616 los arrasa en el multiverso de la locura.": "Where the Avengers were replaced by the Illuminati (Captain Carter, Black Bolt, Reed Richards, Professor X…), who executed their own Strange for using the Darkhold. The 616 Wanda tears through them in Multiverse of Madness.",
  "Las ramas del Vigilante": "The Watcher's branches",
  "Ramas vigiladas por Uatu": "Branches watched over by Uatu",
  "Captain Carter (Peggy con el suero), el Star-Lord T'Challa que convence a Thanos de ser bueno, Infinity Ultron —que gana y amenaza el multiverso entero— y la guerra de Killmonger. Los Guardianes del Multiverso nacen aquí.": "Captain Carter (Peggy with the serum), the Star-Lord T'Challa who talks Thanos into being good, Infinity Ultron — who wins and threatens the entire multiverse — and Killmonger's war. The Guardians of the Multiverse are born here.",
  "El brote cuántico": "The quantum outbreak",
  "En cuarentena": "Quarantined",
  "Hank Pym trae del reino cuántico a una Janet infectada y el virus arrasa: caen Iron Man, el Capi y casi todos. Visión alimenta en secreto a una Wanda zombi; la esperanza es la Gema de la Mente.": "Hank Pym brings an infected Janet back from the Quantum Realm and the virus sweeps through everything: Iron Man, Cap and almost everyone falls. Vision secretly feeds a zombie Wanda; the hope is the Mind Stone.",
  "El original de papel": "The original on paper",
  "El origen de todo": "The origin of everything",
  "El universo de los cómics desde los primeros Fantastic Four: Vengadores fundados por Thor, Iron Man, Hank Pym, la Avispa y Hulk; Ultrón creado por Pym, no por Stark; y una Civil War desatada por el incidente de Stamford.": "The comics universe since the first Fantastic Four issues: Avengers founded by Thor, Iron Man, Hank Pym, the Wasp and Hulk; Ultron created by Pym, not Stark; and a Civil War sparked by the Stamford incident.",
  "Primer paso": "First step",
  "Marca tu primer título": "Mark your first title",
  "Trilogía del Capi": "The Cap trilogy",
  "El primer vengador, Soldado de Invierno y Civil War": "The First Avenger, The Winter Soldier and Civil War",
  "El chasquido": "The Snap",
  "Infinity War y Endgame": "Infinity War and Endgame",
  "Mutante y orgulloso": "Mutant and proud",
  "Toda la saga X-Men": "The whole X-Men saga",
  "Los Defensores": "The Defenders",
  "Las 6 series de Netflix": "All 6 Netflix series",
  "Ruta express": "Express route",
  "Todo lo imprescindible para Doomsday": "Everything essential for Doomsday",
  "Ratón de biblioteca": "Bookworm",
  "Lee 5 cómics esenciales": "Read 5 essential comics",
  "Cien horas": "One hundred hours",
  "100 horas de maratón vistas": "100 marathon hours watched",
  "Media maratón": "Half marathon",
  "La mitad de los títulos": "Half of all titles",
  "Completista": "Completist",
  "Absolutamente todo visto y leído": "Absolutely everything watched and read",
  "El atraco temporal vuelve a la batalla de Nueva York": "The time heist returns to the Battle of New York",
  "El Loki de 2012 escapa con el Teseracto": "The 2012 Loki escapes with the Tesseract",
  "La TVA y los telares del tiempo": "The TVA and the Temporal Loom",
  "El Que Permanece contenía las ramas del multiverso": "He Who Remains kept the multiverse's branches in check",
  "La TVA saca a Wade de su línea temporal": "The TVA pulls Wade out of his timeline",
  "El dispositivo temporal de Cable": "Cable's time-travel device",
  "Una variante de Logan como compañero de viaje": "A Logan variant as travel companion",
  "La línea mutante corregida tras 1973": "The mutant timeline corrected after 1973",
  "Su escena post-créditos abre la puerta a la Tierra mutante": "Its post-credits scene opens the door to the mutant Earth",
  "El Darkhold corrompe a Wanda": "The Darkhold corrupts Wanda",
  "Del hechizo roto a viajar entre universos": "From the broken spell to traveling between universes",
  "Los Spider-Man y villanos de Raimi y Garfield cruzan": "The Raimi and Garfield Spider-Men and villains cross over",
  "Las variantes de Kang y su Concilio": "The Kang variants and their Council",
  "La plaga nace en una rama del Vigilante": "The plague is born in one of the Watcher's branches",
  "La nave de los 4 Fantásticos aparece en la 616": "The Fantastic Four's ship shows up in the 616",
  "La primera familia, rumbo al choque con Doom": "The first family, headed for the clash with Doom",
  "Los Nuevos Vengadores responden a la llamada": "The New Avengers answer the call",
}
