// GENERADO por `npm run episodios` (scripts/episodios.mjs). NO SE EDITA A MANO.
//
// Título latinoamericano de cada episodio (TMDB es-MX) solo donde difiere de
// verdad del de España de episodes.js, por clave "temporada:número".
// Se enseña cuando el país elegido en Ajustes no es España.
export const EPISODIOS_LATAM = {
 "xmen-tas": {
  "1:1": "La Noche de los Centinelas, 1ª Parte",
  "1:2": "La Noche de los Centinelas, 2ª Parte",
  "1:3": "Entra Magneto, 1ª Parte",
  "1:4": "Entra Magneto, 2ª Parte",
  "1:6": "Venganza Fría",
  "1:7": "Isla de Esclavos",
  "1:11": "Días del Futuro Pasado, 1ª Parte",
  "1:12": "Días del Futuro Pasado, 2ª Parte",
  "2:1": "Hasta que la Muerte nos Separe, 1ª Parte",
  "2:2": "Hasta que la Muerte nos Separe, 2ª Parte",
  "2:3": "Lo Que Sea Necesario",
  "2:4": "Rojo Amanecer",
  "2:5": "Malos Recuerdos",
  "2:6": "Cita con X-Ternal",
  "2:7": "Los Fugitivos del Tiempo, 1ª Parte",
  "2:8": "Los Fugitivos del Tiempo, 2ª Parte",
  "2:9": "La Historia de Titania",
  "2:11": "Mojovisión",
  "2:12": "Reunión, 1ª Parte",
  "2:13": "Reunión, 2ª Parte",
  "3:1": "Más Allá del Pasado, 1ª Parte",
  "3:2": "Más Allá del Pasado, 2ª Parte",
  "3:3": "La Leyenda de Fénix, 1ª Parte: El Sacrificio",
  "3:4": "La Leyenda de Fénix, 2ª Parte: El Lado Oscuro",
  "3:5": "La Leyenda de Fénix, 3ª Parte: El Grito de Banshee",
  "3:6": "La Leyenda de Fénix, 4ª Parte: Los Salteadores de Estrellas",
  "3:7": "La Leyenda de Fénix, 5ª Parte: La Hija de la Luz",
  "5:1": "El Convenio Falange, 1ª Parte",
  "5:2": "El Convenio Falange, 2ª Parte"
 },
 "yfnsm": {
  "1:1": "Fantasía asombrosa",
  "1:2": "La suerte de Parker",
  "1:3": "La crisis de la identidad secreta",
  "1:4": "Alcanzando el éxito",
  "1:5": "El Unicornio descontrolado",
  "1:7": "El ascenso del escorpión",
  "1:8": "Red enredada"
 },
 "iamgroot": {
  "1:3": "La búsqueda de Groot",
  "1:4": "Groot toma un baño",
  "2:1": "¿Eres mi Groot?",
  "2:2": "Groot anda husmeando por ahí",
  "2:4": "El dulce de Groot"
 },
 "runaways": {
  "1:3": "Destino",
  "1:10": "Hostil",
  "2:1": "Gimmie Shelter",
  "2:2": "Radio encendida",
  "2:3": "Doble ceros",
  "2:5": "Fondo de roca",
  "2:6": "Enterrar a otro",
  "2:7": "Extremaunción",
  "2:8": "Vida pasada",
  "2:9": "Mandamás",
  "2:10": "Toma de posesión hostil",
  "2:11": "Último vals",
  "2:13": "Separar"
 },
 "aos": {
  "1:4": "Ojo de espía",
  "1:7": "El eje",
  "1:13": "C.A.R.R.I.L.E.S.",
  "1:15": "Sí, señores",
  "1:16": "El fin del comienzo",
  "1:17": "Gira, gira, gira",
  "1:21": "Grupejo"
 },
 "xmen97": {
  "1:4": "Motendo/Vida y muerte (1)",
  "1:5": "Que no se te olvide",
  "1:6": "Vida y muerte (2)",
  "1:8": "La tolerancia es igual a extinción (1)",
  "1:9": "La tolerancia es igual a extinción (2)",
  "1:10": "La tolerancia es igual a extinción (3)"
 },
 "agent-carter": {
  "1:1": "No es el final",
  "1:3": "Tiempo y marea",
  "1:4": "Ataque relámpago",
  "1:6": "Pecado y error",
  "1:7": "Todo mal",
  "1:8": "Palabras de despedida",
  "2:2": "Un vistazo en la oscuridad",
  "2:9": "Algo de música y baile"
 },
 "punisher": {
  "1:4": "Reabastecimiento",
  "1:7": "Punto de mira",
  "1:8": "Arma blanca",
  "1:9": "De frente al enemigo",
  "1:10": "Virtud del vicioso",
  "2:2": "Luchar o correr",
  "2:5": "Cuidado con las jotas",
  "2:7": "Mal día",
  "2:8": "El guardián de mi hermano",
  "2:9": "Ellos o nosotros",
  "2:10": "Las tinieblas del pasado",
  "2:13": "La tempestad"
 },
 "loki2": {
  "1:1": "Uroboros",
  "1:2": "Quebrando a Brad",
  "1:5": "Ciencia/Ficción",
  "1:6": "Un glorioso propósito"
 },
 "whatif": {
  "1:1": "¿Qué pasaría si... la capitana Carter fuera la primera vengadora?",
  "1:4": "¿Qué pasaría si… el Doctor Strange perdiera su corazón en vez de sus manos?"
 },
 "daredevil-ba": {
  "1:2": "Ópticas",
  "1:3": "El vacío de su mano",
  "1:5": "Con interés",
  "1:6": "Fuerza excesiva",
  "1:7": "Arte por el bien del arte",
  "2:1": "La Estrella del Norte"
 },
 "loki1": {
  "1:1": "Un glorioso propósito",
  "1:4": "El evento nexus",
  "1:5": "Un viaje hacia el misterio"
 },
 "wandavision": {
  "1:1": "Filmada con público en vivo",
  "1:3": "Ahora en colores",
  "1:6": "¡Espectacular estreno de Halloween!",
  "1:7": "Abajo de la cuarta pared",
  "1:8": "En el episodio anterior..."
 },
 "fatws": {
  "1:1": "Un nuevo orden mundial",
  "1:2": "El patriota",
  "1:3": "Los entretelones del poder",
  "1:4": "El mundo entero está mirando"
 },
 "hawkeye": {
  "1:1": "Nunca conozcas a tus héroes",
  "1:2": "Escondidas",
  "1:4": "Somos compañeros, ¿verdad?",
  "1:6": "¿Llegó la Navidad?"
 },
 "moonknight": {
  "1:3": "Alguien amistoso",
  "1:5": "El Sanatorio"
 },
 "msmarvel": {
  "1:1": "La nueva generación",
  "1:2": "Destinada",
  "1:3": "Consecuencias",
  "1:4": "Sangre en el ojo",
  "1:5": "El tiempo dirá",
  "1:6": "No hay un normal"
 },
 "shehulk": {
  "1:1": "Un sentimiento normal de ira",
  "1:2": "Leyes sobrehumanas",
  "1:5": "Verde, alegre y estos jeans me quedan ardientes",
  "1:8": "Brinca y Salta",
  "1:9": "¿De quién es este show?"
 },
 "secretinvasion": {
  "1:3": "Traición",
  "1:4": "Amor"
 },
 "echo": {
  "1:1": "Chafá"
 },
 "agatha": {
  "1:1": "Buscas el sendero",
  "1:2": "Círculo de fe / La puerta quiero ver",
  "1:3": "Tras mucho andar / Y tropezar",
  "1:4": "Si no estoy aquí / Mi canto guíe en ti",
  "1:5": "Que despierte / Tu poder",
  "1:6": "Con tu familiar",
  "1:7": "Con la muerte andar",
  "1:8": "Sigueme y tendrás / La gloria al final",
  "1:9": "Doncella, madre, anciana"
 },
 "ironheart": {
  "1:1": "Volver a casa",
  "1:2": "Que la Natalie real se levante",
  "1:3": "Hay peligro, nena",
  "1:5": "El karma no falla",
  "1:6": "Al pasado lo pasado"
 },
 "eyeswakanda": {
  "1:1": "En la guarida del león"
 },
 "wonderman": {
  "1:1": "Matiné",
  "1:2": "Auto-grabación",
  "1:4": "El Portero",
  "1:5": "Evidencia"
 },
 "sm-amigos81": {
  "1:1": "El triunfo del Goblin Verde",
  "1:13": "En Busca de Cráneo Rojo",
  "2:1": "El origen del Hombre de Hielo"
 },
 "ironman94": {
  "1:1": "Y el mar habra de renunciar a sus muertos",
  "1:2": "El ultimo libertador",
  "1:3": "Filtracion de informacion",
  "1:8": "La deserción de Ojo de Halcón",
  "1:9": "El doble de Iron Man (Parte 1)",
  "1:10": "El doble de Iron Man (Parte 2)"
 },
 "spiderman94": {
  "1:1": "La Noche del Lagarto",
  "1:4": "El Doctor Octopus",
  "1:5": "Las Travesuras de Mysterio",
  "1:8": "El Disfraz del Alien, 1ª Parte",
  "1:9": "El Disfraz del Alien, 2ª Parte",
  "1:10": "El Disfraz del Alien, 3ª Parte",
  "1:11": "El Duende, 1ª Parte",
  "1:12": "El Duende, 2ª Parte",
  "1:13": "El Día del Camaleón",
  "2:1": "Los Seis Villanos, 1ª Parte",
  "2:2": "Los Seis Villanos, 2ª Parte",
  "2:4": "La Agenda Mutante",
  "2:5": "La Venganza de los Mutantes",
  "2:7": "La Entrada de Punisher",
  "2:8": "Duelo de Cazadores",
  "2:9": "Blade, el Cazador de Vampiros",
  "2:11": "Lápida del Tiempo",
  "2:12": "Estragos del Tiempo",
  "2:13": "El Grito del Buitre",
  "3:1": "El Doctor Strange",
  "3:3": "El Ataque de Octobot",
  "3:4": "El Duende Verde",
  "3:5": "Ladrones Motorizados",
  "3:6": "Inculpado",
  "3:7": "Un Hombre Sin Miedo",
  "3:8": "El Gran Asesino",
  "3:9": "Tombstone Regresa",
  "3:11": "Carnage",
  "3:13": "La Guerra del Duende",
  "3:14": "Cambio de Vista",
  "4:5": "Compañeros",
  "4:6": "El Regreso de Morbius",
  "4:9": "La Persecución de Mary Jane",
  "4:10": "El Rey de los Lagartos",
  "5:2": "Los Seis Guerreros Olvidados, 1ª Parte",
  "5:3": "Los Seis Guerreros Olvidados, 2ª Parte",
  "5:4": "Los Seis Guerreros Olvidados, 3ª Parte",
  "5:5": "Los Seis Guerreros Luchan Otra Vez",
  "5:7": "El Regreso de Hydro-Man, 1ª Parte",
  "5:8": "El Regreso de Hydro-Man, 2ª Parte",
  "5:12": "Spider-Man y Los Clones"
 },
 "sm-unlimited99": {
  "1:1": "Mundos aparte (primera parte)",
  "1:2": "Mundos aparte (segunda parte)",
  "1:7": "EI grito del Buitre"
 },
 "emh": {
  "2:23": "Los nuevos vengadores"
 },
 "ultimate-sm": {
  "1:1": "Un Gran Poder",
  "1:2": "Una Gran Responsabilidad",
  "1:3": "El Terrible Doctor Doom",
  "1:5": "El Vuelo de la Araña de Hierro",
  "1:6": "Por Qué Odio Educación Física",
  "1:7": "La Exclusiva",
  "1:8": "El Impostor Viste de Negro",
  "1:9": "Viaje de Estudios",
  "1:10": "Un Día Peculiar",
  "1:12": "Tiempo para Mí",
  "1:13": "No Hables con Extraños",
  "1:15": "Sólo Para su Ojo",
  "1:16": "Abajo el Escarabajo",
  "1:17": "Día de Nieve",
  "1:19": "Un Hogar para Hulk",
  "1:21": "Soy el Hombre Araña",
  "1:24": "El Ataque de Escarabajo",
  "1:25": "La Revelación",
  "1:26": "El Duende Verde al Acecho",
  "2:7": "¡Hombraraña!",
  "2:10": "El Hombre Lobo",
  "2:12": "Itsy Bitsy Hombre Araña",
  "2:13": "La Travesía de Puño de Hierro",
  "2:14": "El Increíble Hulk Araña",
  "2:15": "La Trampa Familiar",
  "2:16": "Stan a mi Lado",
  "2:17": "Masacre Regresa",
  "2:18": "La Bomba de Venom",
  "2:19": "Los Guardianes de la Galaxia",
  "2:20": "El Juego Acabó",
  "2:22": "El Regreso del Hombre de Arena",
  "2:23": "Una Segunda Oportunidad",
  "2:24": "El Regreso de los Seis Siniestros",
  "2:25": "Los Comandos Aulladores",
  "2:26": "Ataque Inigualable",
  "4:1": "El Ataque de HYDRA: Parte 1",
  "4:2": "El Ataque de HYDRA: Parte 2",
  "4:8": "El Anti-Venom",
  "4:10": "Los Nuevos Seis Siniestros: Parte 1",
  "4:11": "Los Nuevos Seis Siniestros: Parte 2",
  "4:13": "La Saga Simbionte: Parte 1",
  "4:14": "La Saga Simbionte: Parte 2",
  "4:15": "La Saga Simbionte: Parte 3",
  "4:16": "Regreso al Univers-Araña: Parte 1",
  "4:17": "Regreso al Univers-Araña: Parte 2",
  "4:18": "Regreso al Univers-Araña: Parte 3",
  "4:19": "Regreso al Univers-Araña: Parte 4",
  "4:21": "Los Destructores de Arañas: Parte 1",
  "4:22": "Los Destructores de Arañas: Parte 2",
  "4:23": "Los Destructores de Arañas: Parte 3",
  "4:25": "Día de Graduación: Parte 1",
  "4:26": "Día de Graduación: Parte 2"
 },
 "avengers-assemble": {
  "1:1": "El protocolo de los Vengadores (parte 1)",
  "1:2": "El protocolo de los Vengadores (parte 2)",
  "1:3": "Un ataque fantasma",
  "1:4": "La serpiente de la muerte",
  "1:5": "Disputa de sangre",
  "1:7": "Hiperion",
  "1:8": "Niño molécula",
  "1:10": "El Muerte-destructor",
  "1:14": "El día amnésico de Hulk",
  "1:15": "Planeta Muerte",
  "1:20": "El día del Dios supremo",
  "1:21": "Conforme a las cifras",
  "1:23": "Una cosita",
  "2:3": "Valhalla puede esperar",
  "2:9": "Los Vengadores oscuros",
  "2:12": "La carrera de la Viuda",
  "2:13": "Thanos triunfante",
  "2:16": "Héroes de pacotilla",
  "2:17": "Vengadores Secretos",
  "2:18": "La aparición de Ultrón",
  "2:19": "El nuevo",
  "2:23": "La resistencia final de los Vengadores",
  "2:24": "Los Vengadores en la clandestinidad",
  "2:26": "Mundo de Vengadores",
  "3:7": "Viaje a la Dimensión Oscura."
 },
 "hitmonkey": {
  "1:2": "Luces de neón, gran ciudad",
  "1:3": "La leyenda del mono ebrio",
  "1:5": "Corre, Monkey, corre",
  "1:6": "La larga despedida",
  "1:9": "El final: Parte uno",
  "1:10": "El final: Parte dos",
  "2:1": "Devolver al remitente",
  "2:2": "Adivina quién viene a cenar",
  "2:3": "La cuerda",
  "2:4": "Nunca es demasiado tarde",
  "2:6": "La finca",
  "2:7": "La última cena",
  "2:8": "Centro comercial mental",
  "2:9": "La jungla de hormigón",
  "2:10": "Lecciones de historia"
 }
}
