// GENERADO por `npm run episodios-en` (scripts/episodios-en.mjs). NO SE EDITA A MANO.
//
// Título original en inglés de cada episodio (TMDB en-US) solo donde difiere
// del de España de episodes.js, por clave "temporada:número".
// Se enseña cuando el idioma elegido en Ajustes es English.
export const EPISODIOS_EN = {
 "xmen-tas": {
  "1:1": "Night of the Sentinels (1)",
  "1:2": "Night of the Sentinels (2)",
  "1:3": "Enter Magneto",
  "1:4": "Deadly Reunions",
  "1:5": "Captive Hearts",
  "1:6": "Cold Vengeance",
  "1:7": "Slave Island",
  "1:11": "Days of Future Past (1)",
  "1:12": "Days of Future Past (2)",
  "1:13": "The Final Decision",
  "2:1": "Till Death Do Us Part (1)",
  "2:2": "Till Death Do Us Part (2)",
  "2:3": "Whatever It Takes",
  "2:4": "Red Dawn",
  "2:5": "Repo Man",
  "2:6": "X-Ternally Yours",
  "2:7": "Time Fugitives (1)",
  "2:8": "Time Fugitives (2)",
  "2:9": "A Rogue's Tale",
  "2:10": "Beauty & the Beast",
  "2:12": "Reunion (1)",
  "2:13": "Reunion (2)",
  "3:1": "Out of the Past (1)",
  "3:2": "Out of the Past (2)",
  "3:3": "The Phoenix Saga: Sacrifice (1)",
  "3:4": "The Phoenix Saga: The Dark Shroud (2)",
  "3:5": "The Phoenix Saga: Cry of the Banshee (3)",
  "3:6": "The Phoenix Saga: The Starjammers (4)",
  "3:7": "The Phoenix Saga: Child of Light (5)",
  "5:1": "The Phalanx Covenant (1)",
  "5:2": "The Phalanx Covenant (2)"
 },
 "gifted": {
  "1:1": "eXposed",
  "1:3": "eXodus",
  "1:4": "eXit strategy",
  "1:5": "boXed in",
  "1:6": "got your siX",
  "1:7": "eXtreme measures",
  "1:8": "threat of eXtinction",
  "1:9": "outfoX",
  "1:10": "eXploited",
  "1:11": "3 X 1",
  "1:12": "eXtraction",
  "1:13": "X-roads",
  "2:1": "eMergence",
  "2:2": "unMoored",
  "2:3": "coMplications",
  "2:4": "outMatched",
  "2:5": "afterMath",
  "2:6": "iMprint",
  "2:7": "no Mercy",
  "2:8": "the dreaM",
  "2:9": "gaMe changer",
  "2:10": "eneMy of My eneMy",
  "2:11": "meMento",
  "2:12": "hoMe",
  "2:13": "teMpted",
  "2:14": "calaMity",
  "2:15": "Monsters",
  "2:16": "oMens"
 },
 "yfnsm": {
  "1:1": "Amazing Fantasy",
  "1:2": "The Parker Luck",
  "1:3": "Secret Identity Crisis",
  "1:4": "Hitting the Big Time",
  "1:5": "The Unicorn Unleashed",
  "1:6": "Duel with the Devil",
  "1:7": "Scorpion Rising",
  "1:8": "Tangled Web",
  "1:9": "Hero or Menace",
  "1:10": "If This Be My Destiny..."
 },
 "iamgroot": {
  "1:1": "Groot's First Steps",
  "1:2": "The Little Guy",
  "1:3": "Groot's Pursuit",
  "1:4": "Groot Takes a Bath",
  "1:5": "Magnum Opus",
  "2:1": "Are You My Groot?",
  "2:2": "Groot Noses Around",
  "2:3": "Groot's Snow Day",
  "2:4": "Groot's Sweet Treat",
  "2:5": "Groot and the Great Prophecy"
 },
 "cloakdagger": {
  "1:1": "First Light",
  "1:2": "Suicide Sprints",
  "1:3": "Stained Glass",
  "1:4": "Call/Response",
  "1:5": "Princeton Offense",
  "1:6": "Funhouse Mirrors",
  "1:7": "Lotus Eaters",
  "1:8": "Ghost Stories",
  "1:9": "Back Breaker",
  "1:10": "Colony Collapse",
  "2:1": "Restless Energy",
  "2:2": "White Lines",
  "2:3": "Shadow Selves",
  "2:4": "Rabbit Hold",
  "2:5": "Alignment Chart",
  "2:6": "B Sides",
  "2:7": "Vikingtown Sound",
  "2:8": "Two Player",
  "2:9": "Blue Note",
  "2:10": "Level Up"
 },
 "inhumans": {
  "1:1": "Behold...The Inhumans",
  "1:2": "Those Who Would Destroy Us",
  "1:3": "Divide and Conquer",
  "1:4": "Make Way For... Medusa",
  "1:5": "Something Inhuman This Way Comes...",
  "1:6": "The Gentleman's Name Is Gorgon",
  "1:7": "Havoc in the Hidden Land",
  "1:8": "...And Finally: Black Bolt"
 },
 "runaways": {
  "1:1": "Reunion",
  "1:2": "Rewind",
  "1:4": "Fifteen",
  "1:5": "Kingdom",
  "1:6": "Metamorphosis",
  "1:7": "Refraction",
  "1:9": "Doomsday",
  "1:10": "Hostile",
  "2:1": "Gimme Shelter",
  "2:2": "Radio On",
  "2:3": "Double Zeros",
  "2:4": "Old School",
  "2:5": "Rock Bottom",
  "2:6": "Bury Another",
  "2:7": "Last Rites",
  "2:8": "Past Life",
  "2:9": "Big Shot",
  "2:10": "Hostile Takeover",
  "2:11": "Last Waltz",
  "2:12": "Earth Angel",
  "2:13": "Split Up",
  "3:1": "Smoke and Mirrors",
  "3:2": "The Great Escape",
  "3:3": "Lord of Lies",
  "3:4": "Rite of Thunder",
  "3:5": "Enter the Dreamland",
  "3:6": "Merry Meet Again",
  "3:7": "Left-Hand Path",
  "3:8": "Devil's Torture Chamber",
  "3:9": "The Broken Circle",
  "3:10": "Cheat the Gallows"
 },
 "aos": {
  "1:1": "Pilot",
  "1:3": "The Asset",
  "1:4": "Eye Spy",
  "1:5": "Girl in the Flower Dress",
  "1:6": "FZZT",
  "1:7": "The Hub",
  "1:8": "The Well",
  "1:9": "Repairs",
  "1:10": "The Bridge",
  "1:11": "The Magical Place",
  "1:12": "Seeds",
  "1:13": "T.R.A.C.K.S.",
  "1:15": "Yes Men",
  "1:16": "End of the Beginning",
  "1:17": "Turn, Turn, Turn",
  "1:18": "Providence",
  "1:19": "The Only Light in the Darkness",
  "1:20": "Nothing Personal",
  "1:21": "Ragtag",
  "1:22": "Beginning of the End",
  "2:1": "Shadows",
  "2:2": "Heavy Is the Head",
  "2:3": "Making Friends and Influencing People",
  "2:4": "Face My Enemy",
  "2:5": "A Hen in the Wolf House",
  "2:6": "A Fractured House",
  "2:7": "The Writing on the Wall",
  "2:8": "The Things We Bury",
  "2:9": "...Ye Who Enter Here",
  "2:10": "What They Become",
  "2:11": "Aftershocks",
  "2:12": "Who You Really Are",
  "2:13": "One of Us",
  "2:14": "Love in the Time of Hydra",
  "2:15": "One Door Closes",
  "2:16": "Afterlife",
  "2:18": "The Frenemy of My Enemy",
  "2:19": "The Dirty Half Dozen",
  "2:20": "Scars",
  "3:1": "Laws of Nature",
  "3:2": "Purpose in the Machine",
  "3:3": "A Wanted (Inhu)man",
  "3:4": "Devils You Know",
  "3:5": "4,722 Hours",
  "3:6": "Among Us Hide...",
  "3:7": "Chaos Theory",
  "3:8": "Many Heads, One Tale",
  "3:9": "Closure",
  "3:11": "Bouncing Back",
  "3:12": "The Inside Man",
  "3:13": "Parting Shot",
  "3:14": "Watchdogs",
  "3:15": "Spacetime",
  "3:16": "Paradise Lost",
  "3:17": "The Team",
  "3:18": "The Singularity",
  "3:19": "Failed Experiments",
  "3:20": "Emancipation",
  "3:21": "Absolution (1)",
  "3:22": "Ascension (2)",
  "4:1": "The Ghost",
  "4:2": "Meet the New Boss",
  "4:3": "Uprising",
  "4:4": "Let Me Stand Next to Your Fire",
  "4:5": "Lockup",
  "4:6": "The Good Samaritan",
  "4:7": "Deals with Our Devils",
  "4:8": "The Laws of Inferno Dynamics",
  "4:9": "Broken Promises",
  "4:10": "The Patriot",
  "4:11": "Wake Up",
  "4:12": "Hot Potato Soup",
  "4:13": "BOOM",
  "4:14": "The Man Behind the Shield",
  "4:15": "Self Control",
  "4:16": "What If...",
  "4:17": "Identity and Change",
  "4:18": "No Regrets",
  "4:19": "All the Madame's Men",
  "4:20": "Farewell, Cruel World!",
  "4:21": "The Return",
  "4:22": "World's End",
  "5:1": "Orientation (1)",
  "5:2": "Orientation (2)",
  "5:3": "A Life Spent",
  "5:4": "A Life Earned",
  "5:5": "Rewind",
  "5:6": "Fun & Games",
  "5:7": "Together or Not at All",
  "5:8": "The Last Day",
  "5:9": "Best Laid Plans",
  "5:10": "Past Life",
  "5:11": "All the Comforts of Home",
  "5:12": "The Real Deal",
  "5:14": "The Devil Complex",
  "5:15": "Rise and Shine",
  "5:16": "Inside Voices",
  "5:17": "The Honeymoon",
  "5:18": "All Roads Lead…",
  "5:19": "Option Two",
  "5:20": "The One Who Will Save Us All",
  "5:21": "The Force of Gravity",
  "5:22": "The End",
  "6:1": "Missing Pieces",
  "6:2": "Window of Opportunity",
  "6:3": "Fear and Loathing on the Planet of Kitson",
  "6:4": "Code Yellow",
  "6:5": "The Other Thing",
  "6:6": "Inescapable",
  "6:7": "Toldja",
  "6:8": "Collision Course (1)",
  "6:9": "Collision Course (2)",
  "6:10": "Leap",
  "6:11": "From the Ashes",
  "6:12": "The Sign",
  "6:13": "New Life",
  "7:1": "The New Deal",
  "7:2": "Know Your Onions",
  "7:3": "Alien Commies from the Future!",
  "7:4": "Out of the Past",
  "7:5": "A Trout in the Milk",
  "7:6": "Adapt or Die",
  "7:7": "The Totally Excellent Adventures of Mack and The D",
  "7:8": "After, Before",
  "7:9": "As I Have Always Been",
  "7:10": "Stolen",
  "7:11": "Brand New Day",
  "7:12": "The End Is at Hand",
  "7:13": "What We're Fighting For"
 },
 "xmen97": {
  "1:1": "To Me, My X-Men",
  "1:2": "Mutant Liberation Begins",
  "1:3": "Fire Made Flesh",
  "1:4": "Motendo / Lifedeath (1)",
  "1:5": "Remember It",
  "1:6": "Lifedeath (2)",
  "1:7": "Bright Eyes",
  "1:8": "Tolerance Is Extinction (1)",
  "1:9": "Tolerance Is Extinction (2)",
  "1:10": "Tolerance Is Extinction (3)"
 },
 "agent-carter": {
  "1:1": "Now Is Not the End",
  "1:2": "Bridge and Tunnel",
  "1:3": "Time and Tide",
  "1:4": "The Blitzkrieg Button",
  "1:5": "The Iron Ceiling",
  "1:6": "A Sin to Err",
  "1:7": "SNAFU",
  "1:8": "Valediction",
  "2:1": "The Lady in the Lake",
  "2:2": "A View in the Dark",
  "2:3": "Better Angels",
  "2:4": "Smoke and Mirrors",
  "2:5": "The Atomic Job",
  "2:6": "Life of the Party",
  "2:7": "Monsters",
  "2:8": "The Edge of Mystery",
  "2:9": "A Little Song and Dance",
  "2:10": "Hollywood Ending"
 },
 "daredevil": {
  "1:1": "Into the Ring",
  "1:2": "Cut Man",
  "1:3": "Rabbit in a Snowstorm",
  "1:4": "In the Blood",
  "1:5": "World on Fire",
  "1:6": "Condemned",
  "1:8": "Shadows in the Glass",
  "1:9": "Speak of the Devil",
  "1:10": "Nelson v. Murdock",
  "1:11": "The Path of the Righteous",
  "1:12": "The Ones We Leave Behind",
  "2:2": "Dogs to a Gunfight",
  "2:3": "New York's Finest",
  "2:4": "Penny and Dime",
  "2:6": "Regrets Only",
  "2:8": "Guilty as Sin",
  "2:9": "Seven Minutes in Heaven",
  "2:10": "The Man in the Box",
  "2:11": ".380",
  "2:12": "The Dark at the End of the Tunnel",
  "2:13": "A Cold Day in Hell's Kitchen",
  "3:1": "Resurrection",
  "3:2": "Please",
  "3:3": "No Good Deed",
  "3:4": "Blindsided",
  "3:5": "The Perfect Game",
  "3:6": "The Devil You Know",
  "3:7": "Aftermath",
  "3:8": "Upstairs/Downstairs",
  "3:9": "Revelations",
  "3:11": "Reunion",
  "3:12": "One Last Shot",
  "3:13": "A New Napkin"
 },
 "jessicajones": {
  "1:1": "AKA Ladies Night",
  "1:2": "AKA Crush Syndrome",
  "1:3": "AKA It's Called Whiskey",
  "1:4": "AKA 99 Friends",
  "1:5": "AKA The Sandwich Saved Me",
  "1:6": "AKA You're a Winner!",
  "1:7": "AKA Top Shelf Perverts",
  "1:8": "AKA WWJD?",
  "1:9": "AKA Sin Bin",
  "1:10": "AKA 1,000 Cuts",
  "1:11": "AKA I've Got the Blues",
  "1:12": "AKA Take a Bloody Number",
  "1:13": "AKA Smile",
  "2:1": "AKA Start at the Beginning",
  "2:2": "AKA Freak Accident",
  "2:3": "AKA Sole Survivor",
  "2:4": "AKA God Help the Hobo",
  "2:5": "AKA The Octopus",
  "2:6": "AKA Facetime",
  "2:7": "AKA I Want Your Cray Cray",
  "2:8": "AKA Ain't We Got Fun",
  "2:9": "AKA Shark in the Bathtub, Monster in the Bed",
  "2:10": "AKA Pork Chop",
  "2:11": "AKA Three Lives and Counting",
  "2:12": "AKA Pray for My Patsy",
  "2:13": "AKA Playland",
  "3:1": "AKA The Perfect Burger",
  "3:2": "AKA You're Welcome",
  "3:3": "AKA I Have No Spleen",
  "3:4": "AKA Customer Service is Standing By",
  "3:5": "AKA I Wish",
  "3:6": "AKA Sorry Face",
  "3:7": "AKA The Double Half-Wappinger",
  "3:8": "AKA Camera Friendly",
  "3:9": "AKA I Did Something Today",
  "3:10": "AKA Hero Pants",
  "3:11": "AKA Hellcat",
  "3:12": "AKA A Lotta Worms",
  "3:13": "AKA Everything"
 },
 "lukecage": {
  "1:1": "Moment of Truth",
  "1:2": "Code of the Streets",
  "1:3": "Who's Gonna Take the Weight?",
  "1:4": "Step in the Arena",
  "1:5": "Just to Get a Rep",
  "1:6": "Suckas Need Bodyguards",
  "1:7": "Manifest",
  "1:8": "Blowin' Up the Spot",
  "1:10": "Take It Personal",
  "1:11": "Now You're Mine",
  "1:12": "Soliloquy of Chaos",
  "1:13": "You Know My Steez",
  "2:1": "Soul Brother #1",
  "2:2": "Straighten It Out",
  "2:3": "Wig Out",
  "2:4": "I Get Physical",
  "2:5": "All Souled Out",
  "2:6": "The Basement",
  "2:7": "On and On",
  "2:8": "If It Ain't Rough, It Ain't Right",
  "2:9": "For Pete's Sake",
  "2:10": "The Main Ingredient",
  "2:11": "The Creator",
  "2:12": "Can't Front on Me",
  "2:13": "They Reminisce Over You"
 },
 "ironfist": {
  "1:1": "Snow Gives Way",
  "1:2": "Shadow Hawk Takes Flight",
  "1:3": "Rolling Thunder Cannon Punch",
  "1:4": "Eight Diagram Dragon Palm",
  "1:5": "Under Leaf Pluck Lotus",
  "1:6": "Immortal Emerges from Cave",
  "1:7": "Felling Tree with Roots",
  "1:8": "The Blessing of Many Fractures",
  "1:9": "The Mistress of All Agonies",
  "1:10": "Black Tiger Steals Heart",
  "1:11": "Lead Horse Back to Stable",
  "1:12": "Bar the Big Boss",
  "1:13": "Dragon Plays with Fire",
  "2:1": "The Fury of Iron Fist",
  "2:2": "The City's Not for Burning",
  "2:3": "This Deadly Secret...",
  "2:4": "Target: Iron Fist",
  "2:5": "Heart of the Dragon",
  "2:6": "The Dragon Dies at Dawn",
  "2:7": "Morning of the Mindstorm",
  "2:8": "Citadel on the Edge of Vengeance",
  "2:9": "War Without End",
  "2:10": "A Duel of Iron"
 },
 "punisher": {
  "1:1": "3AM",
  "1:2": "Two Dead Men",
  "1:4": "Resupply",
  "1:6": "The Judas Goat",
  "1:7": "Crosshairs",
  "1:8": "Cold Steel",
  "1:9": "Front Toward Enemy",
  "1:10": "Virtue of the Vicious",
  "1:11": "Danger Close",
  "1:12": "Home",
  "2:1": "Roadhouse Blues",
  "2:2": "Fight or Flight",
  "2:3": "Trouble the Water",
  "2:4": "Scar Tissue",
  "2:5": "One-Eyed Jacks",
  "2:7": "One Bad Day",
  "2:8": "My Brother's Keeper",
  "2:9": "Flustercluck",
  "2:10": "The Dark Hearts of Men",
  "2:11": "The Abyss",
  "2:12": "Collision Course",
  "2:13": "The Whirlwind"
 },
 "loki2": {
  "1:2": "Breaking Brad",
  "1:4": "Heart of the TVA",
  "1:5": "Science/Fiction",
  "1:6": "Glorious Purpose"
 },
 "whatif": {
  "1:1": "What If... Captain Carter Were the First Avenger?",
  "1:2": "What If... T'Challa Became a Star-Lord?",
  "1:3": "What If... The World Lost Its Mightiest Heroes?",
  "1:4": "What If... Doctor Strange Lost His Heart Instead of His Hands?",
  "1:5": "What If... Zombies!?",
  "1:6": "What If... Killmonger Rescued Tony Stark?",
  "1:7": "What If... Thor Were an Only Child?",
  "1:8": "What If... Ultron Won?",
  "1:9": "What If... The Watcher Broke His Oath?",
  "2:1": "What If... Nebula Joined the Nova Corps?",
  "2:2": "What If... Peter Quill Attacked Earth's Mightiest Heroes?",
  "2:3": "What If... Happy Hogan Saved Christmas?",
  "2:4": "What If... Iron Man Crashed Into the Grandmaster?",
  "2:5": "What If... Captain Carter Fought the Hydra Stomper?",
  "2:6": "What If... Kahhori Reshaped the World?",
  "2:7": "What If... Hela Found the Ten Rings?",
  "2:8": "What If... The Avengers Assembled in 1602?",
  "2:9": "What If... Strange Supreme Intervened?",
  "3:1": "What If... The Hulk Fought the Mech Avengers?",
  "3:2": "What If... Agatha Went to Hollywood?",
  "3:3": "What If... The Red Guardian Stopped the Winter Soldier?",
  "3:4": "What If... Howard the Duck Got Hitched?",
  "3:5": "What If... The Emergence Destroyed the Earth?",
  "3:6": "What If... 1872?",
  "3:7": "What If... The Watcher Disappeared? (1)",
  "3:8": "What If... What If? (2)"
 },
 "daredevil-ba": {
  "1:1": "Heaven's Half Hour",
  "1:2": "Optics",
  "1:3": "The Hollow of His Hand",
  "1:5": "With Interest",
  "1:6": "Excessive Force",
  "1:7": "Art for Art's Sake",
  "1:8": "Isle of Joy",
  "1:9": "Straight to Hell",
  "2:1": "The Northern Star",
  "2:2": "Shoot the Moon",
  "2:3": "The Scales & the Sword",
  "2:4": "Gloves Off",
  "2:5": "The Grand Design",
  "2:6": "Requiem",
  "2:7": "The Hateful Darkness",
  "2:8": "The Southern Cross"
 },
 "defenders": {
  "1:1": "The H Word",
  "1:2": "Mean Right Hook",
  "1:3": "Worst Behavior",
  "1:4": "Royal Dragon",
  "1:5": "Take Shelter",
  "1:6": "Ashes, Ashes",
  "1:7": "Fish in the Jailhouse"
 },
 "loki1": {
  "1:1": "Glorious Purpose",
  "1:2": "The Variant",
  "1:4": "The Nexus Event",
  "1:5": "Journey into Mystery",
  "1:6": "For All Time. Always."
 },
 "wandavision": {
  "1:1": "Filmed Before a Live Studio Audience",
  "1:2": "Don't Touch That Dial",
  "1:3": "Now in Color",
  "1:4": "We Interrupt This Program",
  "1:5": "On a Very Special Episode...",
  "1:6": "All-New Halloween Spooktacular!",
  "1:7": "Breaking the Fourth Wall",
  "1:8": "Previously On",
  "1:9": "The Series Finale"
 },
 "fatws": {
  "1:1": "New World Order",
  "1:2": "The Star-Spangled Man",
  "1:3": "Power Broker",
  "1:4": "The Whole World Is Watching",
  "1:5": "Truth",
  "1:6": "One World, One People"
 },
 "hawkeye": {
  "1:1": "Never Meet Your Heroes",
  "1:2": "Hide and Seek",
  "1:3": "Echoes",
  "1:4": "Partners, Am I Right?",
  "1:6": "So This Is Christmas?"
 },
 "moonknight": {
  "1:1": "The Goldfish Problem",
  "1:2": "Summon the Suit",
  "1:3": "The Friendly Type",
  "1:4": "The Tomb",
  "1:5": "Asylum",
  "1:6": "Gods and Monsters"
 },
 "msmarvel": {
  "1:1": "Generation Why",
  "1:2": "Crushed",
  "1:3": "Destined",
  "1:4": "Seeing Red",
  "1:5": "Time and Again",
  "1:6": "No Normal"
 },
 "shehulk": {
  "1:1": "A Normal Amount of Rage",
  "1:2": "Superhuman Law",
  "1:3": "The People vs. Emil Blonsky",
  "1:4": "Is This Not Real Magic?",
  "1:5": "Mean, Green, and Straight Poured into These Jeans",
  "1:6": "Just Jen",
  "1:7": "The Retreat",
  "1:8": "Ribbit and Rip It",
  "1:9": "Whose Show Is This?"
 },
 "secretinvasion": {
  "1:1": "Resurrection",
  "1:2": "Promises",
  "1:3": "Betrayed",
  "1:4": "Beloved",
  "1:5": "Harvest",
  "1:6": "Home"
 },
 "agatha": {
  "1:1": "Seekest Thou the Road",
  "1:2": "Circle Sewn with Fate / Unlock Thy Hidden Gate",
  "1:3": "Through Many Miles / Of Tricks and Trials",
  "1:4": "If I Can't Reach You / Let My Song Teach You",
  "1:5": "Darkest Hour / Wake Thy Power",
  "1:6": "Familiar by Thy Side",
  "1:7": "Death's Hand in Mine",
  "1:8": "Follow Me My Friend / To Glory at the End",
  "1:9": "Maiden Mother Crone"
 },
 "ironheart": {
  "1:1": "Take Me Home",
  "1:2": "Will the Real Natalie Please Stand Up?",
  "1:3": "We in Danger, Girl",
  "1:4": "Bad Magic",
  "1:5": "Karma's a Glitch",
  "1:6": "The Past Is the Past"
 },
 "eyeswakanda": {
  "1:1": "Into the Lion's Den",
  "1:2": "Legends and Lies",
  "1:3": "Lost and Found",
  "1:4": "The Last Panther"
 },
 "wonderman": {
  "1:1": "Matinee",
  "1:2": "Self-Tape",
  "1:4": "Doorman",
  "1:5": "Found Footage",
  "1:6": "Callback"
 },
 "sm-amigos81": {
  "1:1": "Triumph of the Green Goblin",
  "1:2": "The Crime of All Centuries",
  "1:3": "The Fantastic Mr. Frump!",
  "1:4": "Sunfire",
  "1:5": "Swarm",
  "1:6": "7 Little Superheroes",
  "1:7": "Video-Man",
  "1:8": "The Prison Plot",
  "1:9": "Spidey Goes Hollywood",
  "1:10": "The Vengeance of Loki!",
  "1:11": "Knights and Demons",
  "1:12": "Pawns of the Kingpin",
  "1:13": "The Quest of the Red Skull",
  "2:1": "The Origin of the Iceman",
  "2:2": "A Fire-Star is Born",
  "2:3": "Along Came Spidey",
  "3:1": "Spider-Man Unmasked!",
  "3:2": "The Bride of Dracula!",
  "3:3": "The Education of a Superhero",
  "3:4": "Attack of the Arachnoid",
  "3:5": "The Origin of the Spider-Friends",
  "3:6": "Spidey Meets the Girl from Tomorrow",
  "3:7": "The X-Men Adventure",
  "3:8": "Mission: Save the Guardstar"
 },
 "ironman94": {
  "1:1": "And the Sea Shall Give Up Its Dead",
  "1:2": "Rejoice! I Am Ultimo, Thy Deliverer",
  "1:3": "Data In, Chaos Out",
  "1:4": "Silence My Companion, Death My Destination",
  "1:5": "The Grim Reaper Wears a Teflon Coat",
  "1:6": "Enemy Without, Enemy Within",
  "1:7": "The Origin of the Mandarin",
  "1:8": "The Defection of Hawkeye",
  "1:9": "Iron Man to the Second Power (1)",
  "1:10": "Iron Man to the Second Power (2)",
  "1:11": "The Origin of Iron Man (1)",
  "1:12": "The Origin of Iron Man (2)",
  "1:13": "The Wedding of Iron Man",
  "2:1": "The Beast Within",
  "2:2": "Fire and Rain",
  "2:3": "Cell of Iron",
  "2:4": "Not Far from the Tree",
  "2:5": "Beauty Knows No Pain",
  "2:6": "Iron Man, on the Inside",
  "2:7": "Distant Boundaries",
  "2:8": "The Armor Wars (1)",
  "2:9": "The Armor Wars (2)",
  "2:10": "Empowered",
  "2:11": "Hulk Buster",
  "2:12": "Hands of the Mandarin (1)",
  "2:13": "Hands of the Mandarin (2)"
 },
 "f4-94": {
  "1:1": "The Origin of the Fantastic Four (1)",
  "1:2": "The Origin of the Fantastic Four (2)",
  "1:3": "Now Comes the Sub-Mariner",
  "1:4": "Incursion of the Skrull",
  "1:5": "The Silver Surfer and the Coming of Galactus (1)",
  "1:6": "The Silver Surfer and the Coming of Galactus (2)",
  "1:8": "The Mask of Doom (1)",
  "1:9": "The Mask of Doom (2)",
  "1:10": "The Mask of Doom (3)",
  "1:11": "Mole Man",
  "1:12": "Behold the Negative Zone",
  "1:13": "The Silver Surfer and the Return of Galactus",
  "2:1": "And a Blind Man Shall Lead Them",
  "2:2": "Inhumans Saga (1): And the Wind Cries Medusa",
  "2:3": "Inhumans Saga (2): The Inhumans Among Us",
  "2:4": "Inhumans Saga (3): Beware the Hidden Land",
  "2:5": "Worlds Within Worlds",
  "2:6": "To Battle the Living Planet",
  "2:7": "Prey of the Black Panther",
  "2:8": "When Calls Galactus",
  "2:9": "Nightmare in Green",
  "2:10": "Behold, a Distant Star",
  "2:11": "Hopelessly Impossible",
  "2:12": "The Sentry Sinister",
  "2:13": "Doomsday"
 },
 "spiderman94": {
  "1:1": "Night of the Lizard",
  "1:2": "The Spider Slayer (1)",
  "1:3": "Return of the Spider Slayers (2)",
  "1:4": "Doctor Octopus: Armed and Dangerous",
  "1:5": "The Menace of Mysterio",
  "1:6": "The Sting of the Scorpion",
  "1:7": "Kraven the Hunter",
  "1:8": "The Alien Costume (1)",
  "1:9": "The Alien Costume (2)",
  "1:10": "The Alien Costume (3)",
  "1:11": "The Hobgoblin (1)",
  "1:12": "The Hobgoblin (2)",
  "1:13": "Day of the Chameleon",
  "2:1": "Neogenic Nightmare: The Insidious Six",
  "2:2": "Neogenic Nightmare: Battle of the Insidious Six",
  "2:3": "Neogenic Nightmare: Hydro-Man",
  "2:4": "Neogenic Nightmare: The Mutant Agenda",
  "2:5": "Neogenic Nightmare: Mutants' Revenge",
  "2:6": "Neogenic Nightmare: Morbius",
  "2:7": "Neogenic Nightmare: Enter the Punisher",
  "2:8": "Neogenic Nightmare: Duel of the Hunters",
  "2:9": "Neogenic Nightmare: Blade the Vampire Hunter",
  "2:10": "Neogenic Nightmare: The Immortal Vampire",
  "2:11": "Neogenic Nightmare: Tablet of Time",
  "2:12": "Neogenic Nightmare: Ravages of Time",
  "2:13": "Neogenic Nightmare: Shriek of the Vulture",
  "2:14": "Neogenic Nightmare: The Final Nightmare",
  "3:1": "The Sins of the Fathers: Doctor Strange",
  "3:2": "The Sins of the Fathers: Make a Wish (1)",
  "3:3": "The Sins of the Fathers: Attack of the Octobot (2)",
  "3:4": "The Sins of the Fathers: Enter the Green Goblin",
  "3:5": "The Sins of the Fathers: Rocket Racer",
  "3:6": "The Sins of the Fathers: Framed",
  "3:7": "The Sins of the Fathers: The Man Without Fear",
  "3:8": "The Sins of the Fathers: The Ultimate Slayer",
  "3:9": "The Sins of the Fathers: Tombstone",
  "3:10": "The Sins of the Fathers: Venom Returns",
  "3:11": "The Sins of the Fathers: Carnage",
  "3:12": "The Sins of the Fathers: The Spot",
  "3:13": "The Sins of the Fathers: Goblin War! (1)",
  "3:14": "The Sins of the Fathers: Turning Point (2)",
  "4:1": "Partners in Danger: Guilty",
  "4:2": "Partners in Danger: The Cat (1)",
  "4:3": "Partners in Danger: The Black Cat (2)",
  "4:4": "Partners in Danger: The Return of Kraven",
  "4:5": "Partners in Danger: Partners",
  "4:6": "Partners in Danger: The Awakening (1)",
  "4:7": "Partners in Danger: The Vampire Queen (2)",
  "4:8": "Partners in Danger: The Return of the Green Goblin",
  "4:9": "Partners in Danger: The Haunting of Mary Jane Watson",
  "4:10": "Partners in Danger: The Lizard King",
  "4:11": "Partners in Danger: The Prowler",
  "5:1": "The Wedding",
  "5:2": "Six Forgotten Warriors (1)",
  "5:3": "Six Forgotten Warriors (2): Unclaimed Legacy",
  "5:4": "Six Forgotten Warriors (3): Secrets of the Six",
  "5:5": "Six Forgotten Warriors (4): The Six Fight Again",
  "5:6": "Six Forgotten Warriors (5): The Price of Heroism",
  "5:7": "The Return of Hydro-Man (1)",
  "5:8": "The Return of Hydro-Man (2)",
  "5:9": "Secret Wars (1): Arrival",
  "5:10": "Secret Wars (2): The Gauntlet of the Red Skull",
  "5:11": "Secret Wars (3): Doom",
  "5:12": "Spider Wars (1): I Really, Really Hate Clones",
  "5:13": "Spider Wars (2): Farewell, Spider-Man"
 },
 "hulk96": {
  "1:1": "Return of the Beast (1)",
  "1:2": "Return of the Beast (2)",
  "1:3": "Raw Power",
  "1:4": "Helping Hand, Iron Fist",
  "1:5": "Innocent Blood",
  "1:6": "Man to Man, Beast to Beast",
  "1:7": "Doomed",
  "1:8": "Fantastic Fortitude",
  "1:9": "Mortal Bounds",
  "1:10": "And the Wind Cries... Wendigo!",
  "1:11": "Darkness and Light (1)",
  "1:12": "Darkness and Light (2)",
  "1:13": "Darkness and Light (3)",
  "2:1": "A Hulk of a Different Color",
  "2:2": "Down Memory Lane",
  "2:3": "Mind Over Anti-Matter",
  "2:4": "They Call Me Mr. Fixit",
  "2:5": "Fashion Warriors",
  "2:6": "Hollywood Rocks",
  "2:7": "The Lost Village",
  "2:8": "Mission: Incredible"
 },
 "silversurfer98": {
  "1:1": "The Origin of the Silver Surfer (1)",
  "1:2": "The Origin of the Silver Surfer (2)",
  "1:3": "The Origin of the Silver Surfer (3)",
  "1:4": "The Planet of Dr. Moreau",
  "1:5": "Learning Curve (1)",
  "1:6": "Learning Curve (2)",
  "1:7": "Innervisions",
  "1:8": "Antibody",
  "1:9": "Second Foundation",
  "1:10": "Radical Justice",
  "1:11": "Return to Zenn-La",
  "1:12": "The End of Eternity",
  "1:13": "The Forever War"
 },
 "sm-unlimited99": {
  "1:1": "Worlds Apart (1)",
  "1:2": "Worlds Apart (2)",
  "1:3": "Where Evil Nests",
  "1:4": "Deadly Choices",
  "1:5": "Steel Cold Heart",
  "1:6": "Enter the Hunter!",
  "1:7": "Cry Vulture",
  "1:8": "Ill-Met by Moonlight",
  "1:9": "Sustenance",
  "1:10": "Matters of the Heart",
  "1:11": "One is the Loneliest Number",
  "1:12": "Sins of the Fathers",
  "1:13": "Destiny Unleashed (1)"
 },
 "emh": {
  "1:1": "Breakout (1)",
  "1:2": "Breakout (2)",
  "1:3": "Iron Man Is Born",
  "1:4": "Thor the Mighty",
  "1:5": "Hulk Versus the World",
  "1:6": "Meet Captain America",
  "1:7": "The Man in the Ant Hill",
  "1:8": "Some Assembly Required",
  "1:9": "Living Legend",
  "1:10": "Everything Is Wonderful",
  "1:11": "Panther's Quest",
  "1:12": "Gamma World (1)",
  "1:13": "Gamma World (2)",
  "1:14": "Masters of Evil",
  "1:16": "Widow's Sting",
  "1:17": "The Man Who Stole Tomorrow",
  "1:18": "Come the Conqueror",
  "1:19": "The Kang Dynasty",
  "1:20": "The Casket of Ancient Winters",
  "1:23": "The Ultron Imperative",
  "1:24": "This Hostage Earth",
  "1:25": "The Fall of Asgard",
  "1:26": "A Day Unlike Any Other",
  "2:1": "The Private War of Doctor Doom",
  "2:2": "Alone Against A.I.M.",
  "2:3": "Acts of Vengeance",
  "2:4": "Welcome to the Kree Empire",
  "2:5": "To Steal an Ant-Man",
  "2:7": "Who Do You Trust?",
  "2:8": "The Ballad of Beta Ray Bill",
  "2:9": "Nightmare in Red",
  "2:10": "Prisoner of War",
  "2:11": "Infiltration",
  "2:12": "Secret Invasion",
  "2:13": "Along Came a Spider…",
  "2:14": "Behold… The Vision",
  "2:15": "Powerless",
  "2:16": "Assault on 42",
  "2:17": "Ultron Unlimited",
  "2:19": "Emperor Stark",
  "2:20": "Code Red",
  "2:21": "Winter Soldier",
  "2:22": "The Deadliest Man Alive",
  "2:23": "New Avengers",
  "2:24": "Operation Galactic Storm",
  "2:25": "Live Kree or Die",
  "2:26": "Avengers Assemble"
 },
 "ultimate-sm": {
  "1:1": "Great Power",
  "1:2": "Great Responsibility",
  "1:3": "Doomed",
  "1:5": "Flight of the Iron Spider",
  "1:6": "Why I Hate Gym",
  "1:7": "Exclusive",
  "1:8": "Back in Black",
  "1:9": "Field Trip",
  "1:10": "Freaky",
  "1:11": "Venomous",
  "1:12": "Me Time",
  "1:13": "Strange",
  "1:14": "Awesome",
  "1:15": "For Your Eye Only",
  "1:16": "Beetle Mania",
  "1:17": "Snow Day",
  "1:18": "Damage",
  "1:19": "Home Sick Hulk",
  "1:20": "Run Pig Run",
  "1:21": "I Am Spider-Man",
  "1:22": "The Iron Octopus",
  "1:23": "Not a Toy",
  "1:24": "The Attack of the Beetle",
  "1:25": "Revealed",
  "1:26": "The Rise of the Goblin",
  "2:1": "The Lizard",
  "2:3": "The Rhino",
  "2:4": "Kraven the Hunter",
  "2:5": "Hawkeye",
  "2:6": "The Sinister Six",
  "2:7": "Spidah-Man!",
  "2:8": "Carnage",
  "2:9": "House Arrest",
  "2:10": "The Man-Wolf",
  "2:11": "Swarm",
  "2:12": "Itsy Bitsy Spider-Man",
  "2:13": "Journey of the Iron Fist",
  "2:14": "The Incredible Spider-Hulk",
  "2:15": "Stan By Me",
  "2:16": "Ultimate Deadpool",
  "2:17": "Venom Bomb",
  "2:18": "Guardians of the Galaxy",
  "2:19": "The Parent Trap",
  "2:20": "Game Over",
  "2:22": "The Howling Commandos",
  "2:23": "Second Chance Hero",
  "2:24": "Sandman Returns",
  "2:25": "Return of the Sinister Six",
  "2:26": "Ultimate",
  "3:1": "The Return of the Guardians of the Galaxy",
  "3:2": "The Avenging Spider-Man",
  "3:3": "Agent Venom",
  "3:4": "Cloak & Dagger",
  "3:5": "The Next Iron Spider",
  "3:6": "The Vulture",
  "3:7": "The Savage Spider-Man",
  "3:8": "Halloween Night at the Museum",
  "3:9": "New Warriors",
  "3:10": "Nightmare on Christmas",
  "3:11": "The Spider-Verse (1)",
  "3:12": "The Spider-Verse (2)",
  "3:13": "The Spider-Verse (3)",
  "3:14": "The Spider-Verse (4)",
  "3:15": "S.H.I.E.L.D. Academy",
  "3:16": "The Rampaging Rhino",
  "3:18": "Burrito Run",
  "3:19": "Inhumanity",
  "3:20": "Attack of the Synthezoids",
  "3:21": "The Revenge of Arnim Zola",
  "3:22": "Contest of Champions (1)",
  "3:23": "Contest of Champions (2)",
  "3:24": "Contest of Champions (3)",
  "3:25": "Contest of Champions (4)",
  "4:1": "Hydra Attacks (1)",
  "4:2": "Hydra Attacks (2)",
  "4:3": "Miles from Home",
  "4:4": "Iron Vulture",
  "4:5": "Lizards",
  "4:6": "Double Agent Venom",
  "4:7": "Beached",
  "4:8": "Anti-Venom",
  "4:9": "Force of Nature",
  "4:10": "The New Sinister Six (1)",
  "4:11": "The New Sinister Six (2)",
  "4:12": "Agent Web",
  "4:13": "The Symbiote Saga (1)",
  "4:14": "The Symbiote Saga (2)",
  "4:15": "The Symbiote Saga (3)",
  "4:16": "Return to the Spider-Verse (1)",
  "4:17": "Return to the Spider-Verse (2)",
  "4:18": "Return to the Spider-Verse (3)",
  "4:19": "Return to the Spider-Verse (4)",
  "4:20": "Strange Little Halloween",
  "4:21": "The Spider Slayers (1)",
  "4:22": "The Spider Slayers (2)",
  "4:23": "The Spider Slayers (3)",
  "4:24": "The Moon Knight Before Christmas",
  "4:25": "Graduation Day (1)",
  "4:26": "Graduation Day (2)"
 },
 "avengers-assemble": {
  "1:1": "The Avengers Protocol (1)",
  "1:2": "The Avengers Protocol (2)",
  "1:3": "Ghost of a Chance",
  "1:4": "The Serpent of Doom",
  "1:5": "Blood Feud",
  "1:6": "Super Adaptoid",
  "1:8": "Molecule Kid",
  "1:9": "Depth Charge",
  "1:10": "The Doomstroyer",
  "1:11": "Hulked Out Heroes",
  "1:12": "Avengers: Impossible!",
  "1:13": "In Deep",
  "1:14": "Hulk's Day Out",
  "1:15": "Planet Doom",
  "1:16": "Bring on the Bad Guys",
  "1:17": "Savages",
  "1:18": "Mojo World",
  "1:19": "The Ambassador",
  "1:20": "All-Father's Day",
  "1:21": "By the Numbers",
  "1:22": "Guardians & Space Knights",
  "1:23": "One Little Thing",
  "1:24": "Crime and Circuses",
  "1:25": "Exodus",
  "1:26": "The Final Showdown",
  "2:1": "The Arsenal",
  "2:2": "Thanos Rising",
  "2:3": "Valhalla Can Wait",
  "2:4": "Ghosts of the Past",
  "2:5": "Beneath the Surface",
  "2:6": "Nighthawk",
  "2:7": "The Age of Tony Stark",
  "2:8": "Head to Head",
  "2:9": "The Dark Avengers",
  "2:10": "Back to the Learning Hall",
  "2:11": "Downgraded",
  "2:12": "Widow's Run",
  "2:13": "Thanos Triumphant",
  "2:14": "Crack in the System",
  "2:15": "Avengers Disassembled",
  "2:16": "Small Time Heroes",
  "2:17": "Secret Avengers",
  "2:18": "The Ultron Outbreak",
  "2:19": "The New Guy",
  "2:20": "Terminal Velocity",
  "2:21": "Spectrums",
  "2:22": "Midgard Crisis",
  "2:23": "Avengers' Last Stand",
  "2:24": "Avengers Underground",
  "2:25": "New Frontiers",
  "2:26": "Avengers World",
  "3:1": "Adapting to Change",
  "3:2": "The Ultimates",
  "3:3": "Saving Captain Rogers",
  "3:4": "Under Siege",
  "3:5": "The Thunderbolts",
  "3:6": "Thunderbolts Revealed",
  "3:7": "Into the Dark Dimension",
  "3:8": "Dehulked",
  "3:9": "Inhumans Among Us",
  "3:10": "The Inhuman Condition",
  "3:11": "The Kids Are Alright",
  "3:12": "The Conqueror",
  "3:13": "Into The Future",
  "3:14": "Seeing Double",
  "3:15": "A Friend in Need",
  "3:16": "Captain Marvel",
  "3:17": "Panther's Rage",
  "3:18": "Ant-Man Makes It Big",
  "3:19": "The House of Zemo",
  "3:20": "U-Foes",
  "3:21": "Building the Perfect Weapon",
  "3:22": "World War Hulk",
  "3:23": "Civil War (1): The Fall of Attilan",
  "3:24": "Civil War (2): The Mighty Avengers",
  "3:25": "Civil War (3): The Drums of War",
  "3:26": "Civil War (4): Avengers Revolution",
  "4:1": "Avengers No More (1)",
  "4:2": "Avengers No More (2)",
  "4:3": "The Sleeper Awakens",
  "4:4": "Prison Break",
  "4:5": "The Incredible Herc",
  "4:6": "Show Your Work",
  "4:7": "Sneakers",
  "4:8": "Why I Hate Halloween",
  "4:9": "The Once and Future Kang",
  "4:10": "Dimension Z",
  "4:11": "The Most Dangerous Hunt",
  "4:12": "Under the Spell of the Enchantress",
  "4:13": "The Return",
  "4:14": "New Year's Resolution",
  "4:15": "The Eye of Agamotto (1)",
  "4:16": "The Eye of Agamotto (2)",
  "4:17": "Beyond",
  "4:18": "Underworld",
  "4:19": "The Immortal Weapon",
  "4:20": "The Vibranium Coast",
  "4:21": "Weirdworld",
  "4:22": "Westland",
  "4:23": "The Citadel",
  "4:24": "The Wastelands",
  "4:25": "All Things Must End",
  "5:1": "Shadow of Atlantis (1)",
  "5:2": "Shadow of Atlantis (2)",
  "5:3": "Into the Deep",
  "5:4": "The Panther and the Wolf",
  "5:8": "The Night Has Wings",
  "5:9": "Mask of the Panther",
  "5:10": "The Good Son",
  "5:13": "The Last Avenger"
 },
 "gotg-2015": {
  "1:1": "Road to Knowhere",
  "1:2": "Knowhere to Run",
  "1:3": "One in a Million You",
  "1:4": "Take the Milano and Run",
  "1:5": "Can't Fight This Seedling",
  "1:6": "Undercover Angle",
  "1:7": "The Backstabbers",
  "1:8": "Hitchin' a Ride",
  "1:9": "We Are Family",
  "1:10": "Bad Moon Rising",
  "1:11": "Space Cowboys",
  "1:12": "Crystal Blue Persuasion",
  "1:13": "Stuck in the Metal with You",
  "1:14": "Don't Stop Believin'",
  "1:15": "Accidents Will Happen",
  "1:16": "We Are the World Tree",
  "1:17": "Come and Gut Your Love",
  "1:18": "Asgard War (1): Lightnin' Strikes",
  "1:19": "Asgard War (2): Rescue Me",
  "1:20": "Fox on the Run",
  "1:21": "Inhuman Touch",
  "1:22": "Welcome Back",
  "1:23": "I've Been Searching So Long",
  "1:24": "I Feel the Earth Move",
  "1:25": "Won't Get Fooled Again",
  "1:26": "Jingle Bell Rock",
  "2:1": "Stayin' Alive",
  "2:2": "Evolution Rock",
  "2:3": "Lyin' Eyes",
  "2:4": "Free Bird",
  "2:5": "Girls Just Wanna Have Fun",
  "2:6": "Black Helmet Woman",
  "2:7": "Right Place, Wrong Time",
  "2:8": "Me and You and a Dog Named Cosmo",
  "2:9": "Can't Get It Out Of My Head",
  "2:10": "Rock Your Baby",
  "2:11": "Symbiote War (1): Wild World",
  "2:12": "Symbiote War (2): I Will Survive",
  "2:13": "Symbiote War (3): Thunder Road",
  "2:14": "Back in Black",
  "2:15": "Knights in Black Helmets",
  "2:16": "Nova Me, Nova You",
  "2:18": "Destroyer",
  "2:19": "You Can't Always Get What You Want",
  "2:20": "I've Seen All Good People",
  "2:21": "Another One Bites the Dust",
  "2:22": "It's Tricky",
  "2:23": "You're No Good",
  "2:24": "Behind Gold Eyes",
  "2:25": "Unfortunate Son"
 },
 "sm-2017": {
  "1:1": "Horizon High (1)",
  "1:2": "Horizon High (2)",
  "1:3": "Osborn Academy",
  "1:4": "A Day in the Life",
  "1:5": "Party Animals",
  "1:6": "Sandman",
  "1:7": "Symbiotic Relationship",
  "1:8": "Stark Expo",
  "1:10": "Kraven's Amazing Hunt",
  "1:11": "Halloween Moon",
  "1:12": "Spider-Man on Ice",
  "1:15": "The Rise of Doc Ock (1)",
  "1:16": "The Rise of Doc Ock (2)",
  "1:17": "The Rise of Doc Ock (3)",
  "1:18": "The Rise of Doc Ock (4)",
  "1:19": "Spider-Island (1)",
  "1:20": "Spider-Island (2)",
  "1:21": "Spider-Island (3)",
  "1:22": "Spider-Island (4)",
  "1:23": "Spider-Island (5)",
  "1:24": "The Hobgoblin (1)",
  "1:25": "The Hobgoblin (2)",
  "2:1": "How I Thwipped My Summer Vacation",
  "2:2": "Take Two",
  "2:3": "Between an Ock and a Hard Place",
  "2:4": "Rise Above It All",
  "2:5": "School of Hard Knocks",
  "2:6": "Dead Man’s Party",
  "2:7": "Venom Returns",
  "2:8": "Bring on the Bad Guys (1)",
  "2:9": "Bring on the Bad Guys (2)",
  "2:10": "Bring on the Bad Guys (3)",
  "2:11": "Bring on the Bad Guys (4)",
  "2:12": "Brain Drain",
  "2:13": "The Living Brain",
  "2:14": "The Day Without Spider-Man",
  "2:15": "My Own Worst Enemy",
  "2:16": "Critical Update",
  "2:17": "A Troubled Mind",
  "2:18": "Cloak and Dagger",
  "2:20": "Brand New Day",
  "2:21": "The Cellar",
  "2:22": "The Road to Goblin War",
  "2:23": "Goblin War (1)",
  "2:24": "Goblin War (2)",
  "2:25": "Goblin War (3)",
  "2:26": "Goblin War (4)",
  "3:1": "Web of Venom",
  "3:2": "Amazing Friends",
  "3:3": "Vengeance of Venom",
  "3:4": "Spider-Man Unmasked",
  "3:5": "Generations",
  "3:6": "Maximum Venom"
 },
 "modok": {
  "1:1": "If This Be… M.O.D.O.K.!",
  "1:2": "The M.O.D.O.K. That Time Forgot!",
  "1:3": "Beware What from Portal Comes!",
  "1:4": "If Saturday Be... For The Boys!",
  "1:5": "If Bureaucracy Be... Thy Death!",
  "1:6": "Tales from the Great Bar-Mitzvah War!",
  "1:7": "This Man... This Makeover!",
  "1:8": "O, Were Blood Thicker Than Robot Juice!",
  "1:9": "What Menace Doth the Mailman Deliver!",
  "1:10": "Days of Future M.O.D.O.K.s!"
 },
 "hitmonkey": {
  "1:1": "Pilot",
  "1:2": "Bright Lights, Big City",
  "1:3": "Legend of the Drunken Monkey",
  "1:4": "The Code",
  "1:5": "Run Monkey Run",
  "1:6": "The Long Goodbye",
  "1:7": "Sayonara Monkey",
  "1:8": "Home Sweet Home",
  "1:9": "The End (1)",
  "1:10": "The End (2)"
 },
 "spidey-equipo": {
  "1:1": "Spidey to the Power of Three",
  "1:2": "Panther Patience",
  "1:3": "Superhero Hiccups",
  "1:4": "Lost and Found",
  "1:5": "Doc Ock’s Super Octopus",
  "1:6": "Attack of the Green Giggles",
  "1:7": "Bug in the System",
  "1:8": "Test Your Super Strength",
  "1:9": "Pecking Prankster Pigeons",
  "1:10": "Green Thumb",
  "1:11": "Mother's Day Mayhem",
  "1:12": "Not-So-Fun House",
  "1:13": "Camping Conundrum",
  "1:14": "The Great Green Crime Spree",
  "1:15": "Rocket Rhino!",
  "1:16": "Trick or TRACE-E",
  "1:17": "Gob-zilla",
  "1:18": "Speedy Spidey Delivery",
  "1:19": "Good Guy Gobby",
  "1:20": "Spider Monkey",
  "1:21": "CAT-astrophe",
  "1:22": "Swing with a Stomp",
  "1:23": "A Very Spidey Christmas",
  "1:24": "Gobby on Ice",
  "1:25": "Going Green",
  "1:26": "Coming Clean",
  "1:27": "Web Beard’s Treasure",
  "1:28": "Washed Away",
  "1:29": "Spin Rushes In",
  "1:30": "Bridge Bandit",
  "1:31": "Art Attack!",
  "1:32": "Puppy Pandemonium",
  "1:33": "Goblin Island",
  "1:34": "Doc Ock and the Shocktobots",
  "1:35": "Peter's Pendant Predicament",
  "1:37": "Itsy-Bitsy Spiders",
  "1:38": "Gobby's Rotten Pumpkin Hunt",
  "1:39": "The Wozzlesnook",
  "1:40": "Superhero Switcheroo",
  "1:41": "Aunt May's Mess",
  "1:42": "Foam Sweet Foam",
  "1:43": "Freeze! It's Team Spidey",
  "1:44": "A Sticky Situation",
  "1:45": "Rhinoctopus",
  "1:46": "A Pumpkin Problem",
  "1:47": "Catch and Release",
  "1:48": "Construction Destruction",
  "1:49": "Parade Panic",
  "1:50": "The Case of the Burgling Book Bandit",
  "2:1": "Electro's Gotta Glow",
  "2:2": "Black Cat Chaos",
  "2:3": "Lights Out",
  "2:4": "Sandman Won't Share!",
  "2:5": "Bootsie's Day Out",
  "2:6": "Trouble at Tony's",
  "2:7": "Sonic Boom Boom",
  "2:8": "Mini Golf Goof",
  "2:9": "Li'l Hulk",
  "2:10": "Surprise Party Surprise",
  "2:11": "Can't Stop Dancing!",
  "2:12": "The Ant Thief",
  "2:13": "Sand Trapped",
  "2:14": "Too Much Fun",
  "2:15": "Halted Holiday",
  "2:16": "Merry Spidey Christmas",
  "2:17": "An Egg-Cellent Adventure",
  "2:18": "The Hangout Headache",
  "2:19": "Follow That Sea Monster!",
  "2:20": "It's Bad to be Gooed",
  "2:21": "Liberty on the Loose",
  "2:22": "Green Goblin's Dino Disaster",
  "2:23": "Spidey Tidies Up",
  "2:24": "Oh No, Tomatoes!",
  "2:25": "Clean Power",
  "2:26": "Doc Ock & The Rocktobots",
  "2:27": "Pirate Plunder Blunder",
  "2:28": "Bad Bot",
  "2:29": "Spin Saves the Day",
  "2:30": "Water Woes",
  "2:31": "Tunnel Trouble",
  "2:32": "Mystery on Goblin Island",
  "2:33": "The Maltese Kitten",
  "2:34": "A Day With Black Panther",
  "2:35": "The New Villain in Town",
  "2:36": "Spidey Cat",
  "2:37": "A Syrupy Solution",
  "2:38": "Little Ant, Big Problem",
  "2:39": "Ock Tower",
  "2:40": "Outsmarted by Art",
  "2:41": "Super Scooter",
  "2:42": "The Lost Web Shooter",
  "2:43": "Catnap Caper",
  "2:44": "Bunny Bonanza",
  "2:45": "Dino-Rama",
  "2:46": "Daytime at Nighttime",
  "2:47": "Stolen WEB-Quarters",
  "2:48": "Spideys in Space!",
  "2:49": "Hide & Seek",
  "2:50": "Whale of a Time",
  "2:51": "Rollin Rhino",
  "2:52": "The Octopus and the Kitty Cat",
  "2:53": "Go with the Lava Flow",
  "2:54": "An Un-bee-lievable Rosh Hashanah",
  "2:55": "Bootsie's Haunted Adventure",
  "2:56": "Too Many Tricks, Not Enough Treats",
  "2:57": "How to Train Your Doggy",
  "2:58": "Dome Alone",
  "3:1": "The Friendly Neighborhood",
  "3:2": "Flight of the Butterflies",
  "3:3": "Ock's Obey Ray",
  "3:4": "Lemur at Large",
  "3:5": "Tree Trouble",
  "3:6": "Stuck in Space",
  "3:7": "Antarctic Adventure",
  "3:8": "Let It Snowball, Let It Snowball, Let It Snowball",
  "3:9": "Bubble Trouble",
  "3:10": "Rainy River Run",
  "3:11": "The Rhino and the Goose",
  "3:12": "Dog vs Cat",
  "3:13": "Journey Through Zola",
  "3:14": "Villaintines Day",
  "3:15": "Now You See Me, Now You Don't",
  "3:16": "Meet Squirrel Girl",
  "3:17": "Car-Tastrophe",
  "3:18": "Sandman and the Tortoise",
  "3:19": "Tiny Car Caper",
  "3:20": "Toothy Fairy Tricks",
  "3:21": "Picture Perfect Pandemonium",
  "3:22": "Catch That Panther Pod",
  "3:24": "Aunt May's Birthday Blowout",
  "3:25": "Freeze, It's Dock Ock!",
  "3:26": "Go, Go, Jeff",
  "3:27": "Zola's Novel Idea",
  "3:28": "Greatest Hits",
  "3:29": "Go Dino-Webs Go!",
  "3:30": "Ghost in the Museum",
  "3:31": "Grow Webs Grow",
  "3:32": "Rio in Space",
  "3:33": "The Goblin and the Geyser",
  "3:34": "Skeleton Stomp",
  "3:35": "Fool's Gold",
  "3:36": "The Sundae Save",
  "3:37": "Adventures in Fossil Hunting",
  "3:38": "Lizard's Buggy Bonanza",
  "3:39": "Odd Bot Team Up",
  "3:40": "The Lost King",
  "3:41": "The Curse of the Corn Dog King",
  "3:42": "Zola's Halloween Heist",
  "3:43": "Too Many Zolas",
  "3:44": "Electro's Glow Show",
  "3:45": "Robo-Spideys",
  "3:46": "Saber-Toothed Kitten",
  "3:47": "Tree House Takeover",
  "3:48": "The Incredible Shrinking Zola",
  "3:49": "Moon Girl and the Dino Dilemma",
  "3:50": "Hulk's Squirrley Switch",
  "3:51": "A Snow Day for Aunt May",
  "3:52": "Hanukkah Heist",
  "3:53": "Tricky Tricky Trapster",
  "3:54": "Tractor Beam Trouble",
  "3:55": "The Campout Mystery",
  "3:56": "Gobby's Metal Menace",
  "3:57": "Dinosaurs on the Loose",
  "3:58": "WEB-STER'S Big Bad Bug",
  "3:59": "Groundhog's Day Out",
  "3:60": "Ploofy Power",
  "4:1": "Voyage to Spider Island",
  "4:2": "Superhero Soak",
  "4:3": "Giant-Sized Lizard",
  "4:4": "Rhino's Wild Bunch",
  "4:5": "The Bots vs. Ock",
  "4:6": "The Battery Boost",
  "4:7": "King Lizard",
  "4:8": "Go Rhino Go",
  "4:9": "Campout Chaos",
  "4:10": "Panther Pod to the Rescue",
  "4:11": "Two Teleporters Too Many",
  "4:12": "Dinos Are Forever",
  "4:13": "The Lost Lair of Web-Beard",
  "4:14": "Captain Gobby",
  "4:15": "Mixing Up Trouble",
  "4:16": "To Catch a Cat",
  "4:17": "How to Catch a Caterpillar",
  "4:18": "A Jellyfish Tale",
  "4:19": "Night of the Goblins",
  "4:20": "Bat Attitude"
 }
}
