// GENERADO por `npm run plataformas` (scripts/paises.mjs). NO SE EDITA A MANO.
//
// Plataforma de suscripción de cada título por país, según TMDB/JustWatch.
// España sigue mandando desde el campo `plat` de data.js (curado a mano);
// este mapa es lo que se enseña cuando el país elegido en Ajustes es otro.
// Caduca solo: los catálogos cambian cada mes.
export const PAISES = [{"id":"ES","nombre":"España"},{"id":"AR","nombre":"Argentina"},{"id":"BO","nombre":"Bolivia"},{"id":"CL","nombre":"Chile"},{"id":"CO","nombre":"Colombia"},{"id":"CR","nombre":"Costa Rica"},{"id":"EC","nombre":"Ecuador"},{"id":"SV","nombre":"El Salvador"},{"id":"US","nombre":"Estados Unidos"},{"id":"GT","nombre":"Guatemala"},{"id":"HN","nombre":"Honduras"},{"id":"MX","nombre":"México"},{"id":"NI","nombre":"Nicaragua"},{"id":"PA","nombre":"Panamá"},{"id":"PY","nombre":"Paraguay"},{"id":"PE","nombre":"Perú"},{"id":"DO","nombre":"República Dominicana"},{"id":"UY","nombre":"Uruguay"},{"id":"VE","nombre":"Venezuela"}]
export const PLATAFORMAS = {
 "ES": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Netflix",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Prime Video",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "Disney+ / HBO Max / Movistar+",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en España",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Disney+ / HBO Max / Movistar+",
  "sm-raimi1": "Solo alquiler",
  "sm-raimi2": "Solo alquiler",
  "sm-raimi3": "Solo alquiler",
  "asm1": "Disney+ / Netflix",
  "asm2": "Disney+ / Netflix",
  "venom1": "Solo alquiler",
  "venom2": "Disney+ / Prime Video / HBO Max",
  "morbius": "Disney+ / Prime Video / HBO Max",
  "madameweb": "Prime Video",
  "venom3": "Netflix",
  "kraven": "RTVE Play gratis",
  "nwh": "Disney+ / HBO Max / Movistar+",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+ / RTVE Play gratis",
  "moongirl": "Disney+"
 },
 "AR": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Argentina",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Universal+",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max / Movistar TV",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Movistar TV",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max / Movistar TV",
  "venom2": "Prime Video / ViX / Movistar TV",
  "morbius": "Movistar TV / Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Universal+ / Movistar TV / Mercado Play gratis",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "BO": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Bolivia",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "CL": {
  "first-class": "Disney+ / Movistar TV",
  "origins-wolverine": "Disney+ / Movistar TV",
  "xmen1": "Disney+ / Movistar TV",
  "x2": "Disney+ / Movistar TV",
  "last-stand": "Disney+ / Movistar TV",
  "the-wolverine": "Disney+ / Movistar TV",
  "dofp": "Disney+ / Movistar TV",
  "apocalypse": "Disney+ / Movistar TV",
  "dark-phoenix": "Disney+ / Movistar TV",
  "deadpool1": "Disney+ / Movistar TV",
  "deadpool2": "Disney+ / Movistar TV",
  "new-mutants": "Disney+ / Movistar TV",
  "logan": "Disney+ / Movistar TV",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+ / Movistar TV",
  "oneshot-carter": "Disney+ / Movistar TV",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+ / Movistar TV",
  "ironman1": "Disney+ / Movistar TV",
  "ironman2": "Disney+ / Movistar TV",
  "thor1": "Disney+ / Movistar TV",
  "hulk": "Solo alquiler",
  "oneshot-consultor": "Movistar TV",
  "avengers1": "Disney+ / Movistar TV",
  "oneshot-item47": "Disney+ / Movistar TV",
  "ironman3": "Disney+ / Movistar TV",
  "oneshot-rey": "Disney+ / Movistar TV",
  "thor2": "Disney+ / Movistar TV",
  "cap2": "Disney+ / Movistar TV",
  "gotg1": "Disney+ / Movistar TV",
  "gotg2": "Disney+ / Movistar TV",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+ / Movistar TV",
  "antman1": "Disney+ / Movistar TV",
  "civilwar": "Disney+ / Movistar TV",
  "blackwidow": "Disney+ / Movistar TV",
  "blackpanther": "Disney+ / Movistar TV",
  "homecoming": "HBO Max / Movistar TV / Claro video",
  "inhumans": "Disney+",
  "drstrange": "Disney+ / Movistar TV",
  "ragnarok": "Disney+ / Movistar TV",
  "team-darryl": "Disney+ / Movistar TV",
  "cloakdagger": "Disney+",
  "runaways": "No está en Chile",
  "antman2": "Disney+ / Movistar TV",
  "infinitywar": "Disney+ / Movistar TV",
  "endgame": "Disney+ / Movistar TV",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+ / Movistar TV",
  "shangchi": "Disney+ / Movistar TV",
  "fatws": "Disney+",
  "lovethunder": "Disney+ / Movistar TV",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max / Movistar TV",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Movistar TV",
  "asm2": "Prime Video / HBO Max / Mercado Play gratis",
  "venom1": "HBO Max / Movistar TV",
  "venom2": "Prime Video / ViX / Mercado Play gratis",
  "morbius": "Movistar TV / Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Universal+ / Movistar TV / Mercado Play gratis",
  "mom": "Disney+ / Movistar TV",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+ / Movistar TV",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+ / Movistar TV",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+ / Movistar TV",
  "ff2007": "Disney+ / Movistar TV",
  "ff2015": "Disney+ / Movistar TV",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "CO": {
  "first-class": "Disney+ / Movistar TV",
  "origins-wolverine": "Disney+ / Movistar TV",
  "xmen1": "Disney+ / Movistar TV",
  "x2": "Disney+ / Movistar TV",
  "last-stand": "Disney+ / Movistar TV",
  "the-wolverine": "Disney+ / Movistar TV",
  "dofp": "Disney+ / Movistar TV",
  "apocalypse": "Disney+ / Movistar TV",
  "dark-phoenix": "Disney+ / Movistar TV",
  "deadpool1": "Disney+ / Movistar TV",
  "deadpool2": "Disney+ / Movistar TV",
  "new-mutants": "Disney+ / Movistar TV",
  "logan": "Disney+ / Movistar TV",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+ / Movistar TV",
  "oneshot-carter": "Disney+ / Movistar TV",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+ / Movistar TV",
  "ironman1": "Disney+ / Movistar TV",
  "ironman2": "Disney+ / Movistar TV",
  "thor1": "Disney+ / Movistar TV",
  "hulk": "Solo alquiler",
  "oneshot-consultor": "Movistar TV",
  "avengers1": "Disney+ / Movistar TV",
  "oneshot-item47": "Disney+ / Movistar TV",
  "ironman3": "Disney+ / Movistar TV",
  "oneshot-rey": "Disney+ / Movistar TV",
  "thor2": "Disney+ / Movistar TV",
  "cap2": "Disney+ / Movistar TV",
  "gotg1": "Disney+ / Movistar TV",
  "gotg2": "Disney+ / Movistar TV",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+ / Movistar TV",
  "antman1": "Disney+ / Movistar TV",
  "civilwar": "Disney+ / Movistar TV",
  "blackwidow": "Disney+ / Movistar TV",
  "blackpanther": "Disney+ / Movistar TV",
  "homecoming": "HBO Max / Claro video",
  "inhumans": "Disney+",
  "drstrange": "Disney+ / Movistar TV",
  "ragnarok": "Disney+ / Movistar TV",
  "team-darryl": "Disney+ / Movistar TV",
  "cloakdagger": "Disney+",
  "runaways": "No está en Colombia",
  "antman2": "Disney+ / Movistar TV",
  "infinitywar": "Disney+ / Movistar TV",
  "endgame": "Disney+ / Movistar TV",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+ / Movistar TV",
  "shangchi": "Disney+ / Movistar TV",
  "fatws": "Disney+",
  "lovethunder": "Disney+ / Movistar TV",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Movistar TV",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max / Movistar TV",
  "venom2": "Prime Video / ViX / Mercado Play gratis",
  "morbius": "Movistar TV / Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Universal+ / Movistar TV / Mercado Play gratis",
  "mom": "Disney+ / Movistar TV",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+ / Movistar TV",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+ / Movistar TV",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+ / Movistar TV",
  "ff2007": "Disney+ / Movistar TV",
  "ff2015": "Disney+ / Movistar TV",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "CR": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Costa Rica",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "EC": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Movistar TV",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max / Movistar TV",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Ecuador",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max / Movistar TV",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Movistar TV",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max / Claro video",
  "venom2": "Prime Video / ViX / Movistar TV",
  "morbius": "Movistar TV / Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Movistar TV / Claro video / Mercado Play gratis",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "SV": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en El Salvador",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "US": {
  "first-class": "Disney+ / HBO Max",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+ / HBO Max",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Hulu",
  "legion": "Hulu",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+ / Hulu",
  "ironman2": "Disney+ / Hulu",
  "oneshot-martillo": "Disney+",
  "thor1": "Disney+ / Hulu",
  "hulk": "Disney+ / Hulu",
  "oneshot-consultor": "Disney+",
  "avengers1": "Disney+ / Hulu",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+ / Hulu",
  "jessicajones": "Disney+ / Hulu",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+ / Starz",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "team-thor": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+ / Hulu",
  "homecoming": "Disney+ / Netflix",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Hulu",
  "runaways": "Tubi gratis",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Disney+",
  "sm-raimi1": "Disney+ / Hulu",
  "sm-raimi2": "Disney+ / Hulu",
  "sm-raimi3": "Disney+ / Hulu",
  "asm1": "Disney+",
  "asm2": "Disney+",
  "venom1": "Disney+",
  "venom2": "Disney+ / Starz",
  "morbius": "Disney+ / Prime Video",
  "madameweb": "Disney+",
  "venom3": "Disney+ / Netflix",
  "kraven": "Disney+",
  "nwh": "Disney+ / Starz",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+ / Hulu",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+ / Hulu",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "xmen-evolution": "Disney+",
  "wolverine-xmen": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+ / The Roku Channel gratis",
  "modok": "Hulu",
  "hitmonkey": "Hulu",
  "spidey-equipo": "Disney+ / Hulu",
  "moongirl": "Disney+"
 },
 "GT": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Guatemala",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "HN": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Honduras",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "MX": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max / Claro video",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en México",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Claro video",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Universal+ / Mercado Play gratis",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "NI": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Nicaragua",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "PA": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Panamá",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "PY": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Paraguay",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "PE": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Perú",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX / Claro video",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max / Claro video",
  "venom2": "Prime Video / ViX / Mercado Play gratis",
  "morbius": "Mercado Play gratis",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Claro video / Mercado Play gratis",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "DO": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en República Dominicana",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "UY": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Uruguay",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / Mercado Play gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Mercado Play gratis",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Mercado Play gratis",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "VE": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "oneshot-carter": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "oneshot-item47": "Disney+",
  "ironman3": "Disney+",
  "oneshot-rey": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "HBO Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "team-darryl": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Venezuela",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video / ViX gratis",
  "sm-raimi1": "Prime Video / HBO Max / ViX",
  "sm-raimi2": "Prime Video / HBO Max",
  "sm-raimi3": "Prime Video / HBO Max / ViX",
  "asm1": "HBO Max / ViX",
  "asm2": "Prime Video / HBO Max / ViX",
  "venom1": "HBO Max",
  "venom2": "Prime Video / ViX",
  "morbius": "Solo alquiler",
  "madameweb": "Solo alquiler",
  "venom3": "Prime Video",
  "kraven": "Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "ff2005": "Disney+",
  "ff2007": "Disney+",
  "ff2015": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 }
}
