// GENERADO por `npm run plataformas` (scripts/paises.mjs). NO SE EDITA A MANO.
//
// Plataforma de suscripción de cada título por país, según TMDB/JustWatch.
// España sigue mandando desde el campo `plat` de data.js (curado a mano);
// este mapa es lo que se enseña cuando el país elegido en Ajustes es otro.
// Caduca solo: los catálogos cambian cada mes.
export const PAISES = [{"id":"ES","nombre":"España"},{"id":"CL","nombre":"Chile"},{"id":"MX","nombre":"México"},{"id":"AR","nombre":"Argentina"},{"id":"CO","nombre":"Colombia"},{"id":"PE","nombre":"Perú"}]
export const PLATAFORMAS = {
 "ES": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Solo alquiler",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Prime Video",
  "avengers1": "Disney+",
  "ironman3": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "Disney+ / Star+",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en España",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en España",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Disney+ / Star+",
  "nwh": "Disney+ / Star+",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en España",
  "doomsday": "No está en España",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "CL": {
  "first-class": "Disney+ / Movistar+",
  "origins-wolverine": "Disney+ / Movistar+",
  "xmen1": "Disney+ / Movistar+",
  "x2": "Disney+ / Movistar+",
  "last-stand": "Disney+ / Movistar+",
  "the-wolverine": "Disney+ / Movistar+",
  "dofp": "Disney+ / Movistar+",
  "apocalypse": "Disney+ / Movistar+",
  "dark-phoenix": "Disney+ / Movistar+",
  "deadpool1": "Disney+ / Movistar+",
  "deadpool2": "Disney+ / Movistar+",
  "new-mutants": "Disney+ / Movistar+",
  "logan": "Disney+ / Movistar+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+ / Movistar+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+ / Movistar+",
  "ironman1": "Disney+ / Movistar+",
  "ironman2": "Disney+ / Movistar+",
  "thor1": "Disney+ / Movistar+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+ / Movistar+",
  "ironman3": "Disney+ / Movistar+",
  "thor2": "Disney+ / Movistar+",
  "cap2": "Disney+ / Movistar+",
  "gotg1": "Disney+ / Movistar+",
  "gotg2": "Disney+ / Movistar+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+ / Movistar+",
  "antman1": "Disney+ / Movistar+",
  "civilwar": "Disney+ / Movistar+",
  "blackwidow": "Disney+ / Movistar+",
  "blackpanther": "Disney+ / Movistar+",
  "homecoming": "Max / Movistar+",
  "inhumans": "Disney+",
  "drstrange": "Disney+ / Movistar+",
  "ragnarok": "Disney+ / Movistar+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Chile",
  "antman2": "Disney+ / Movistar+",
  "infinitywar": "Disney+ / Movistar+",
  "endgame": "Disney+ / Movistar+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en Chile",
  "wandavision": "Disney+",
  "eternals": "Disney+ / Movistar+",
  "shangchi": "Disney+ / Movistar+",
  "fatws": "Disney+",
  "lovethunder": "Disney+ / Movistar+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video",
  "nwh": "Movistar+",
  "mom": "Disney+ / Movistar+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+ / Movistar+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+ / Movistar+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en Chile",
  "doomsday": "No está en Chile",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "MX": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "ironman3": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "Max / Claro video",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en México",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en México",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video",
  "nwh": "Solo alquiler",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en México",
  "doomsday": "No está en México",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "AR": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "ironman3": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Argentina",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en Argentina",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video",
  "nwh": "Movistar+",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en Argentina",
  "doomsday": "No está en Argentina",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "CO": {
  "first-class": "Disney+ / Movistar+",
  "origins-wolverine": "Disney+ / Movistar+",
  "xmen1": "Disney+ / Movistar+",
  "x2": "Disney+ / Movistar+",
  "last-stand": "Disney+ / Movistar+",
  "the-wolverine": "Disney+ / Movistar+",
  "dofp": "Disney+ / Movistar+",
  "apocalypse": "Disney+ / Movistar+",
  "dark-phoenix": "Disney+ / Movistar+",
  "deadpool1": "Disney+ / Movistar+",
  "deadpool2": "Disney+ / Movistar+",
  "new-mutants": "Disney+ / Movistar+",
  "logan": "Disney+ / Movistar+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+ / Movistar+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+ / Movistar+",
  "ironman1": "Disney+ / Movistar+",
  "ironman2": "Disney+ / Movistar+",
  "thor1": "Disney+ / Movistar+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+ / Movistar+",
  "ironman3": "Disney+ / Movistar+",
  "thor2": "Disney+ / Movistar+",
  "cap2": "Disney+ / Movistar+",
  "gotg1": "Disney+ / Movistar+",
  "gotg2": "Disney+ / Movistar+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+ / Movistar+",
  "antman1": "Disney+ / Movistar+",
  "civilwar": "Disney+ / Movistar+",
  "blackwidow": "Disney+ / Movistar+",
  "blackpanther": "Disney+ / Movistar+",
  "homecoming": "Max / Claro video",
  "inhumans": "Disney+",
  "drstrange": "Disney+ / Movistar+",
  "ragnarok": "Disney+ / Movistar+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Colombia",
  "antman2": "Disney+ / Movistar+",
  "infinitywar": "Disney+ / Movistar+",
  "endgame": "Disney+ / Movistar+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en Colombia",
  "wandavision": "Disney+",
  "eternals": "Disney+ / Movistar+",
  "shangchi": "Disney+ / Movistar+",
  "fatws": "Disney+",
  "lovethunder": "Disney+ / Movistar+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video",
  "nwh": "Movistar+",
  "mom": "Disney+ / Movistar+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+ / Movistar+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+ / Movistar+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en Colombia",
  "doomsday": "No está en Colombia",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 },
 "PE": {
  "first-class": "Disney+",
  "origins-wolverine": "Disney+",
  "xmen1": "Disney+",
  "x2": "Disney+",
  "last-stand": "Disney+",
  "the-wolverine": "Disney+",
  "dofp": "Disney+",
  "apocalypse": "Disney+",
  "dark-phoenix": "Disney+",
  "deadpool1": "Disney+",
  "deadpool2": "Disney+",
  "new-mutants": "Disney+",
  "logan": "Disney+",
  "gifted": "Disney+",
  "legion": "Disney+",
  "xmen-tas": "Disney+",
  "xmen97": "Disney+",
  "cap1": "Disney+",
  "agent-carter": "Disney+",
  "capmarvel": "Disney+",
  "ironman1": "Disney+",
  "ironman2": "Disney+",
  "thor1": "Disney+",
  "hulk": "Solo alquiler",
  "avengers1": "Disney+",
  "ironman3": "Disney+",
  "thor2": "Disney+",
  "cap2": "Disney+",
  "gotg1": "Disney+",
  "gotg2": "Disney+",
  "iamgroot": "Disney+",
  "aos": "Disney+",
  "daredevil": "Disney+",
  "jessicajones": "Disney+",
  "lukecage": "Disney+",
  "ironfist": "Disney+",
  "defenders": "Disney+",
  "punisher": "Disney+",
  "ultron": "Disney+",
  "antman1": "Disney+",
  "civilwar": "Disney+",
  "blackwidow": "Disney+",
  "blackpanther": "Disney+",
  "homecoming": "Max",
  "inhumans": "Disney+",
  "drstrange": "Disney+",
  "ragnarok": "Disney+",
  "cloakdagger": "Disney+",
  "runaways": "No está en Perú",
  "antman2": "Disney+",
  "infinitywar": "Disney+",
  "endgame": "Disney+",
  "loki1": "Disney+",
  "whatif": "Disney+",
  "zombies": "Disney+",
  "yfnsm": "No está en Perú",
  "wandavision": "Disney+",
  "eternals": "Disney+",
  "shangchi": "Disney+",
  "fatws": "Disney+",
  "lovethunder": "Disney+",
  "moonknight": "Disney+",
  "ffh": "Netflix / Prime Video",
  "nwh": "Claro video",
  "mom": "Disney+",
  "hawkeye": "Disney+",
  "shehulk": "Disney+",
  "wakandaforever": "Disney+",
  "echo": "Disney+",
  "msmarvel": "Disney+",
  "ironheart": "Disney+",
  "secretinvasion": "Disney+",
  "marvels": "Disney+",
  "holiday": "Disney+",
  "werewolf": "Disney+",
  "wonderman": "Disney+",
  "quantumania": "Disney+",
  "loki2": "Disney+",
  "deadpool3": "Disney+",
  "gotg3": "Disney+",
  "agatha": "Disney+",
  "daredevil-ba": "Disney+",
  "punisher-olk": "Disney+",
  "bravenewworld": "Disney+",
  "thunderbolts": "Disney+",
  "eyeswakanda": "Disney+",
  "ff": "Disney+",
  "brandnewday": "No está en Perú",
  "doomsday": "No está en Perú",
  "sm-amigos81": "Disney+",
  "ironman94": "Disney+",
  "f4-94": "Disney+",
  "spiderman94": "Disney+",
  "hulk96": "Disney+",
  "silversurfer98": "Disney+",
  "sm-unlimited99": "Disney+",
  "emh": "Disney+",
  "ultimate-sm": "Disney+",
  "avengers-assemble": "Disney+",
  "hulk-smash": "Disney+",
  "gotg-2015": "Disney+",
  "sm-2017": "Disney+",
  "modok": "Disney+",
  "hitmonkey": "Disney+",
  "spidey-equipo": "Disney+",
  "moongirl": "Disney+"
 }
}
