// GENERADO por `npm run titulos-en` (scripts/titulos-en.mjs). NO SE EDITA A MANO.
//
// Título en inglés (TMDB en-US) solo donde difiere de verdad del de España
// de data.js. Se enseña cuando el idioma elegido en Ajustes es English.
export const TITULOS_EN = {
 "first-class": "X-Men: First Class",
 "origins-wolverine": "X-Men Origins: Wolverine",
 "x2": "X2",
 "last-stand": "X-Men: The Last Stand",
 "the-wolverine": "The Wolverine",
 "dofp": "X-Men: Days of Future Past",
 "apocalypse": "X-Men: Apocalypse",
 "dark-phoenix": "Dark Phoenix",
 "new-mutants": "The New Mutants",
 "gifted": "The Gifted (S1–S2)",
 "legion": "Legion (S1–S3)",
 "xmen-tas": "X-Men: The Animated Series",
 "cap1": "Captain America: The First Avenger",
 "agent-carter": "Agent Carter (S1–S2)",
 "capmarvel": "Captain Marvel",
 "hulk": "The Incredible Hulk",
 "avengers1": "The Avengers",
 "thor2": "Thor: The Dark World",
 "cap2": "Captain America: The Winter Soldier",
 "gotg1": "Guardians of the Galaxy",
 "gotg2": "Guardians of the Galaxy Vol. 2",
 "iamgroot": "I Am Groot (shorts)",
 "aos": "Agents of S.H.I.E.L.D. (S1–S7)",
 "daredevil": "Daredevil (S1–S3)",
 "jessicajones": "Jessica Jones (S1–S3)",
 "lukecage": "Luke Cage (S1–S2)",
 "ironfist": "Iron Fist (S1–S2)",
 "punisher": "The Punisher (S1–S2)",
 "ultron": "Avengers: Age of Ultron",
 "civilwar": "Captain America: Civil War",
 "blackwidow": "Black Widow",
 "cloakdagger": "Cloak & Dagger (S1–S2)",
 "runaways": "Runaways (S1–S3)",
 "antman2": "Ant-Man and the Wasp",
 "infinitywar": "Avengers: Infinity War",
 "endgame": "Avengers: Endgame",
 "loki1": "Loki (S1)",
 "whatif": "What If...? (S1–S3)",
 "yfnsm": "Your Friendly Neighborhood Spider-Man (S1)",
 "wandavision": "WandaVision",
 "shangchi": "Shang-Chi and the Legend of the Ten Rings",
 "fatws": "The Falcon and the Winter Soldier",
 "moonknight": "Moon Knight",
 "ffh": "Spider-Man: Far From Home",
 "mom": "Doctor Strange in the Multiverse of Madness",
 "hawkeye": "Hawkeye",
 "shehulk": "She-Hulk: Attorney at Law",
 "secretinvasion": "Secret Invasion",
 "holiday": "The Guardians of the Galaxy Holiday Special",
 "quantumania": "Ant-Man and the Wasp: Quantumania",
 "loki2": "Loki (S2)",
 "deadpool3": "Deadpool & Wolverine",
 "gotg3": "Guardians of the Galaxy Vol. 3",
 "agatha": "Agatha All Along",
 "daredevil-ba": "Daredevil: Born Again (S1–S2)",
 "bravenewworld": "Captain America: Brave New World",
 "ff": "The Fantastic 4: First Steps",
 "doomsday": "Avengers: Doomsday",
 "sm-amigos81": "Spider-Man and His Amazing Friends",
 "ironman94": "Iron Man: The Animated Series",
 "f4-94": "Fantastic Four (1994)",
 "spiderman94": "Spider-Man: The Animated Series",
 "hulk96": "The Incredible Hulk (1996)",
 "sm-unlimited99": "Spider-Man Unlimited (Unlimited)",
 "emh": "The Avengers: Earth's Mightiest Heroes",
 "avengers-assemble": "Avengers",
 "hulk-smash": "Hulk and the Agents of S.M.A.S.H.",
 "gotg-2015": "Guardians of the Galaxy (2015)",
 "sm-2017": "Spider-Man (2017)",
 "spidey-equipo": "Spidey and His Amazing Friends",
 "moongirl": "Moon Girl and Devil Dinosaur"
}
