// GENERADO por `npm run titulos` (scripts/titulos.mjs). NO SE EDITA A MANO.
//
// Título latinoamericano (TMDB es-MX) solo donde difiere de verdad del de
// España de data.js. Se enseña cuando el país elegido en Ajustes no es España.
export const TITULOS_LATAM = {
 "origins-wolverine": "X-Men orígenes: Wolverine",
 "last-stand": "X-Men 3: La Batalla Final",
 "the-wolverine": "Wolverine: Inmortal",
 "dark-phoenix": "X-Men: Dark Phoenix",
 "logan": "Logan: Wolverine",
 "gifted": "The Gifted: Los Elegidos (T1–T2)",
 "oneshot-carter": "Marvel One-Shot: Agente Carter",
 "ironman1": "Iron Man: El hombre de hierro",
 "oneshot-martillo": "Marvel One-Shot: Algo gracioso sucedió en la búsqueda del Martillo de Thor",
 "hulk": "Hulk: El hombre increíble",
 "oneshot-consultor": "Marvel One-Shot: El Consultor",
 "avengers1": "Avengers: Los Vengadores",
 "oneshot-item47": "Marvel One-Shot: El Objeto 47",
 "oneshot-rey": "Marvel One-Shot: Que viva el rey",
 "thor2": "Thor: Un mundo oscuro",
 "cap2": "Capitán América y el Soldado del Invierno",
 "gotg2": "Guardianes de la Galaxia volumen 2",
 "iamgroot": "Yo soy Groot (cortos)",
 "ultron": "Avengers 2: Era de Ultrón",
 "antman1": "Ant-Man: El hombre Hormiga",
 "team-thor": "Marvel One-Shot: El Equipo Thor (cortos)",
 "blackwidow": "Black Widow",
 "blackpanther": "Pantera Negra",
 "homecoming": "Spider-Man: De regreso a casa",
 "inhumans": "Inhumanos",
 "drstrange": "Doctor Strange: Hechicero supremo",
 "team-darryl": "Marvel One-Shot: El Equipo Darryl",
 "antman2": "Ant-Man 2: La Avispa",
 "infinitywar": "Avengers: Infinity War",
 "endgame": "Avengers: Endgame",
 "yfnsm": "Tu amigo y vecino Spider-Man (T1)",
 "wandavision": "WandaVision",
 "fatws": "Falcon y el Soldado del Invierno",
 "lovethunder": "Thor: Amor y Trueno",
 "moonknight": "Moon Knight",
 "peter-lista": "La lista de pendientes de Peter (corto)",
 "ffh": "Spider-Man 2: Lejos de Casa",
 "nwh": "Spider-Man: Sin camino a casa",
 "hawkeye": "Hawkeye",
 "shehulk": "She-Hulk: Defensora de héroes",
 "wakandaforever": "Pantera Negra: Wakanda por siempre",
 "holiday": "Guardianes de la Galaxia: Especial de las fiestas",
 "werewolf": "Hombre Lobo por la noche",
 "quantumania": "Ant-Man and the Wasp: Quantumania",
 "deadpool3": "Deadpool & Wolverine",
 "gotg3": "Guardianes de la Galaxia volumen 3",
 "agatha": "Agatha en todas partes",
 "punisher-olk": "The Punisher: La última muerte",
 "bravenewworld": "Capitán América: Un nuevo mundo",
 "eyeswakanda": "Los ojos de Wakanda",
 "ff": "Los 4 Fantásticos: Primeros pasos",
 "brandnewday": "Spider-Man: Un nuevo día",
 "doomsday": "Avengers: Doomsday",
 "sm-amigos81": "El Hombre-Araña y sus Sorprendentes Amigos",
 "spiderman94": "El Hombre Araña: La serie animada",
 "sm-unlimited99": "El Hombre-Araña: Sin Limites",
 "emh": "Los Vengadores: Los héroes más poderosos del planeta",
 "sm-2017": "Spider-Man de Marvel (2017)",
 "spidey-equipo": "Spidey y sus Sorprendentes Amigos",
 "moongirl": "Moon Girl y Devil, el dinosaurio"
}
